### ISSUE TITLE
Doesn't seem to work on 10.13.4 (High Sierra)

### ISSUE THREAD

**Issue by StephanMeijer** [rgov/Thunderbolt3Unblocker#15]
Same as previous project: this doesn't seem to work under 10.13.4

**Comment by rgov** [comment]
Hi Stephan. What is the previous project? What doesn't work? What were you expecting to happen? What happens instead? You need to provide more details, I have no idea what you are talking about.

Before, you edited your post, you wrote

> `backup found`
> `unknown command`
> `patching...%`

But none of this is output that Thunderbolt 3 Unblocker produces.
