### ISSUE TITLE
Crashes on macOS Mojave beta

### ISSUE THREAD

**Issue by Loneshade** [rgov/Thunderbolt3Unblocker#18]
Hey, It seems to crash on Mojave every time it is installed.

**Comment by Loneshade** [comment]
When going through terminal it shows this and then immediately reboots, good thing I filmed it.

KernelCache ID: 2DF3967A74F1F4F5360042CDB36294AF
Kext with invalid signatured (-67050) allowed: <OSKext 0x7ff149772c60 [0x7fff98dc38d0]> { URL = "Thunderbolt3Unblocker.kext/ -- file:///Library/Extensions/", ID = "es.govost.ryan.Thunderbolt3Unblocker" }

**Comment by rgov** [comment]
Confirmed, but the kernel development kit is not available right now for Beta 2. It looks like it's violating NX protections during patching.

**Comment by mzjlswatt** [comment]
i heve the same problem

**Comment by Loneshade** [comment]
Not sure if anyone has managed to get there thunderbolt 3 unlocked on Mojave, as this method doesn't work yet. I have been using Kext Utility to install a hacked version of the thunderbolt kext. It will do until this is back work =]

**Comment by Juldik** [comment]
Can you share the steps, how to use Kext Utility to hack it on Mojave? @Loneshade thx.

**Comment by Loneshade** [comment]
Make a backup of your IOThunderboltFamily.kext 
Open the IOThunderboltFamily.Kext with a hex editor such at iHex

Find 55 48 89 E5 41 57 41 56 41 55 41 54 53 48 81 EC 28 01  and replace with 55 48 89 E5 31 C0 5D C3 41 55 41 54 53 48 81 EC 28 01 

save this file. Keeping the kext name the same this is the new file you will use in Kext Utility. Just drag it over and let it install the kext.

**Comment by Michaelkire** [comment]
Do we have an update on this? I'm very interested in having it working on Mojave as well

**Comment by rgov** [comment]
Like I said, xnu sources are not yet available for Mojave and I haven't identified a solution.

**Comment by gekowa** [comment]
> Make a backup of your IOThunderboltFamily.kext
> Open the IOThunderboltFamily.Kext with a hex editor such at iHex
> 
> Find 55 48 89 E5 41 57 41 56 41 55 41 54 53 48 81 EC 28 01 and replace with 55 48 89 E5 31 C0 5D C3 41 55 41 54 53 48 81 EC 28 01
> 
> save this file. Keeping the kext name the same this is the new file you will use in Kext Utility. Just drag it over and let it install the kext.

It doesn't work. Actually this is what tb3-enabler does, right?

**Comment by rgov** [comment]
I have released a [new version](
https://github.com/rgov/Thunderbolt3Unblocker/releases/tag/v0.0.4) which should work on macOS Mojave. I also expect that it will work on High Sierra, but I have not tested it.

Before testing, please be sure that you are not running a modified (patched) copy of IOThunderboltFamily.kext.
