### ISSUE TITLE
10.13.5 does not appear to work

### ISSUE THREAD

**Issue by cliffporterx** [rgov/Thunderbolt3Unblocker#19]
Tried to use with 10.13.5 which was released recently and it does not appear to work on it.  Might need an update for compatibility.

**Comment by rgov** [comment]
I have shipped my eGPU elsewhere so I cannot very easily test. Could you describe how it doesn’t work?

Do you have any logs? Steps to follow to demonstrate the issue?

**Comment by mirkojuergens** [comment]
In the first place, the tb16 does not appear under Unsupported Thunderbolt devices anymore. I don't know if this will cause a problem.

**Comment by rgov** [comment]
Could you please follow these steps?

1. Uninstall Thunderbolt 3 Unblocker
2. Attach all Thunderbolt 3 peripherals and reboot your computer
3. Open your System Report and export it (File → Save...)
4. Detach the Thunderbolt 3 peripherals
5. Install and activate Thunderbolt 3 Unblocker
6. Re-attach the Thunderbolt 3 peripherals
7. Refresh the System Report (⌘R) and export the new report
8. Reply here and attach both system reports

This will give me the information I need to look at.

**Comment by mirkojuergens** [comment]
i had to change the file extension from *.spx to *.txt

[before.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/2105913/before.txt)
[after.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/2105912/after.txt)

**Comment by rgov** [comment]
Yes, it does not appear that your machine is detecting the Thunderbolt 3 peripheral at all, so Thunderbolt 3 Unblocker has nothing to do. It's not something I believe Thunderbolt 3 Unblocker can fix.

Maybe you could find out more on the egpu.io forum?

**Comment by rgov** [comment]
However, I'll be sure to test it out when I get my Thunderbolt 3 setup back online (in a few months, unfortunately). Alternatively, you could ask on egpu.io if anyone is successfully using Thunderbolt 3 Unblocker on 10.13.5.

**Comment by mirkojuergens** [comment]
Thanks nevertheless

**Comment by rgov** [comment]
Hey @mirkojuergens, check out a new driver for the TB16: https://support.displaylink.com/forums/287786-displaylink-feature-suggestions/suggestions/33252664-macos-high-sierra-10-13-4 Let me know if it fixes the issue for you.
