### ISSUE TITLE
gsidrv.kext does not appear in strict exception list for architecture: x86_64

### ISSUE THREAD

**Issue by kulmam92** [rgov/Thunderbolt3Unblocker#22]
I'm on 10.12.6 (16G1510) and got below error when I try to run commend after copying the file to designated location.

$ sudo sh -c 'chown -R root:wheel /Library/Extensions/Thunderbolt3Unblocker.kext && \
> kextcache -i / && \
> kextload -b es.govost.ryan.Thunderbolt3Unblocker'
Password:
gsidrv.kext does not appear in strict exception list for architecture: x86_64
kext-dev-mode allowing invalid signature -67049 0xFFFFFFFFFFFEFA17 for kext gsidrv.kext
gsidrv.kext does not appear in strict exception list for architecture: x86_64
KernelCache ID: 30CC90E62C716004FDC631BA7CEA4218
disk0s3 didn't unmount, leaving mounted

Can you help me to fix this?

**Comment by rgov** [comment]
I suspect that is unrelated to this project. When you invalidate the kext cache, the system rebuilds it, and that involves re-processing every installed kext. 

Does the kextcache command actually fail, and stop Thunderbolt 3 Unblocker from loading, or does it load? I’m not sure it works on 10.12, I can’t remember.
