### ISSUE TITLE
⚠️ 10.13.6 update to 10.14 will repeatedly panic, UPGRADE kext or UNINSTALL before you update

### ISSUE THREAD

**Issue by u0x01** [rgov/Thunderbolt3Unblocker#23]

**Comment by sxcsfan** [comment]
If you didn't uninstall the kext and performed 10.14 installation like me, you will see a boot loop at the final steps of os x installation. Just shut the mac down, press shift key to enter the safe mode, uninstall the kext file and restart the system, everything will be fine.

**Comment by u0x01** [comment]
I did NVRAM rest. Then could be enter system but skipped system upgrade guide.  So I decided reinstall all system.

**Comment by sxcsfan** [comment]
The upgrade guide did appear with the safe mode way, just FYI.

**Comment by rgov** [comment]
Thanks for filing this. I'll try to add a feature that addresses this (until 10.14 support arrives).

**Comment by rgov** [comment]
The [latest release](
https://github.com/rgov/Thunderbolt3Unblocker/releases/tag/v0.0.3) improves things. *It is still not compatible with Mojave**, but it should make it safer to upgrade between system versions.

**Comment by chaoskcw** [comment]
Hi

Can you help, I am unable to uninstall as per the instructions. I upgraded to Mojave then had boot issues. All attempts to locate the .kext file failed (not in extensions) but kernel kept trying to load it. 

I downloaded latest copy and installed that in extensions. 

Now I boot

Tried to uninstall as per kextunload commands, but it always fails to find anything to unload.

How can I remove this so its never loaded again ? 

Thanks,

**Comment by rgov** [comment]
Try `find /Library /System/Library -iname Thunderbolt3Unblocker.kext`. It will write out the path of where the kext is installed, if it is installed. You can then delete these files. Afterwards you can run `sudo kextcache -i /` and then reboot.

If you cannot find any file, then any boot issues you have are unrelated. 

Do not install it again until 10.14 is supported.

**Comment by rgov** [comment]
I have released a [new version](
https://github.com/rgov/Thunderbolt3Unblocker/releases/tag/v0.0.4) which should work on macOS Mojave. I also expect that it will work on High Sierra, but I have not tested it.

Before testing, please be sure that you are not running a modified (patched) copy of IOThunderboltFamily.kext.

**Comment by u0x01** [comment]
tested on my macbook pro 15 inch 2018, passed.
good job!!! @rgov  thanks again!
