### ISSUE TITLE
Mojave users can try tb3-enabler

### ISSUE THREAD

**Issue by u0x01** [rgov/Thunderbolt3Unblocker#25]
see: https://github.com/KhaosT/tb3-enabler
should be working.

**Comment by rgov** [comment]
The update is tracked in another issue. I am waiting for the 10.14 sources to be posted.

**Comment by sxcsfan** [comment]
Macbook Pro 13 inch 2018 not working, seems there are some other mechanism added for 2018 models. A funny fact is, I deleted IOThunderboltFamily.kext from S/L/E and rebuild all the caches, but after a reboot, if you check from kextstat the original kext still loaded but in the system report, IOThunderboltFamily.kext no longer in the extension list.

**Comment by sxcsfan** [comment]
Highly likely, makes me wonder this live patch approach would work on 10.14 or not. 
But I didn't try the tb3enabler way on 10.13 so I'm not sure kext patching works or not on 2018 models with high sierra.

**Comment by u0x01** [comment]
I think 10.13 should be working like thunderblot3unbolcker.

**Comment by sxcsfan** [comment]
A few updates, a member at egpu.io posted [another hex string](https://egpu.io/forums/mac-setup/enabling-unsupported-tb3-devices-in-general-on-mac-os-mojave-like-was-done-w-tb3-enabler-py/#post-44187) for mojave, I tried but no luck with my 2018 macbook pro.

FROM `55 48 89 E5 41 57 41 56 41 55 41 54 53 48 81 EC 98 01` 
TO      `55 48 89 E5 31 C0 5D C3 41 55 41 54 53 48 81 EC 98 01`

It seems bypass a different function in IOThunderboltFamily.kext.
![image](https://user-images.githubusercontent.com/472125/46185788-0c698300-c30e-11e8-9f7f-6fd44151031d.png)

**Comment by rgov** [comment]
You might find a different forum like eGPU.io a more appropriate venue for discussing this. Your posts don't have anything to do with Thunderbolt 3 Unblocker, and it's not super useful for my bug tracker to be used as a forum for a different project.

**Comment by rgov** [comment]
I have released a [new version](
https://github.com/rgov/Thunderbolt3Unblocker/releases/tag/v0.0.4) which should work on macOS Mojave. I also expect that it will work on High Sierra, but I have not tested it.

Before testing, please be sure that you are not running a modified (patched) copy of IOThunderboltFamily.kext.
