### ISSUE TITLE
v0.0.4 does not work with 2018 15" MBP

### ISSUE THREAD

**Issue by Michaelkire** [rgov/Thunderbolt3Unblocker#26]
Hey. 
I saw that you released a new version that should support Mojave, which I immediately tried.
Unfortunately it crashes on startup with the following error:

`/ locked; waiting for lock.
Lock acquired; proceeding.
Kext with invalid signatured (-67054) allowed: <OSKext 0x7fd494fb83e0 [0x7fff90b048e0]> { URL = "IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/", ID = "com.apple.iokit.IOThunderboltFamily" }
KernelCache ID: 31F5F4688211E28855B99E7DA6867700
Kext with invalid signatured (-67054) allowed: <OSKext 0x7fa947badf90 [0x7fff90b048e0]> { URL = "IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/", ID = "com.apple.iokit.IOThunderboltFamily" }
Kext with invalid signatured (-67050) allowed: <OSKext 0x7fa9478b13c0 [0x7fff90b048e0]> { URL = "Thunderbolt3Unblocker.kext/ -- file:///Library/Extensions/", ID = "es.govost.ryan.Thunderbolt3Unblocker" }
es.govost.ryan.Thunderbolt3Unblocker failed to load - (libkern/kext) kext (kmod) start/stop routine failed; check the system/kernel logs for errors or try kextutil(8).` 

Then I checked logs and got:

`2018-09-28 08:32:04.564605+0200  localhost kernel[0]: Kext es.govost.ryan.Thunderbolt3Unblocker start failed (result 0x5).
2018-09-28 08:32:04.564607+0200  localhost kernel[0]: Kext es.govost.ryan.Thunderbolt3Unblocker failed to load (0xdc008017).
2018-09-28 08:32:04.564610+0200  localhost kernel[0]: Failed to load kext es.govost.ryan.Thunderbolt3Unblocker (error 0xdc008017).`

**Comment by u0x01** [comment]
latest version wokring on my macbook 15 inch 2018.

**Comment by Loneshade** [comment]
> @Michaelkire Please run the `kextload` command again and then afterwards run `sudo dmesg`. You can paste the output to [Gist](https://gist.github.com) and link to it here, or attach it as a file.
> 
> If you previously tried v0.0.3, please also run `sudo nvram -d t3u-incompatible` before running `kextload`.

Hey @rgov I have the same issue as @Michaelkire I am running on a 2018 iMac. I did the sudo dmesg it is here <script src="https://gist.github.com/Loneshade/308bb2df6f8a6e10bdf2212c0e44ca56.js"></script>

**Comment by rgov** [comment]
Thanks. The log shows that it is successfully patching IOThunderboltFamily. Can you unplug your Thunderbolt 3 device and plug it back in and confirm that it shows up in the system profile without "(Unsupported)" next to it?

**Comment by Michaelkire** [comment]
https://gist.github.com/Michaelkire/6eb58767bad3aba3371640928254774c

Seems like it's working for me too now. Thanks a lot :)
At least it didn't say any errors (except for invalid kext signature). Although I can't check if it's actually working until Monday.

**Comment by rgov** [comment]
I'm closing this issue because there doesn't seem to be any evidence that it is not working. Please write back if you find more.

The invalid kext signature error can be ignored; Apple will not give me a kext signing certificate so I cannot eliminate it.
