### ISSUE TITLE
Latest version doesn't work for keyboard and display

### ISSUE THREAD

**Issue by t3b4n** [rgov/Thunderbolt3Unblocker#27]
I uninstalled the kext before updating to Mojave. After the update, I downloaded the new version and installed it. The device is recognized and appears as active in the system report, my mouse and iPhone  work over USB, but my keyboard and display port display don't.

Device: Dell TB16 thunderbolt dock.
Computer: Macbook pro 15 inch with touch bar 2016

**Comment by rgov** [comment]
If you search for Dell TB16 in other issues you will see that this video is not supported on this device due to a separate change that Apple made and which is unrelated to this project. Sorry I can’t be more helpful.

**Comment by rgov** [comment]
Hi @t3b4n, do you want to try installing this updated driver on Mojave and let me know if it works?

Here's the driver: 
http://www.displaylink.com/downloads/file?id=1237

Here's the support document from DisplayLink:

https://support.displaylink.com/forums/287786-displaylink-feature-suggestions/suggestions/33252664-macos-high-sierra-10-13-4

**Comment by t3b4n** [comment]
Hi, Ryan.

Thanks for the link, but it’s still not working for me. I disconnected the dock, installed the new driver, rebooted and connected all again and nothing new happend, it’s just as before.
