### ISSUE TITLE
reboot MacBook and TB3 dock not support until re-plugin cable

### ISSUE THREAD

**Issue by cos003** [rgov/Thunderbolt3Unblocker#30]
my environment: 
MacBook Pro 15, 2018 
macOS Mojave 10.14.1 (18B75)
dock: "HP Elite Zbook Thunderbolt 3 Dock" 

it works well after your solution, thanks! only 1 issue, it will not work when restart MacBook, until I unplug and plug the thunderbolt3 cable again. 
Is it a known issue? how to fix it ? thanks.

**Comment by cos003** [comment]
HP ZBook 150W/200W Thunderbolt 3 Dock

**Comment by i5ean** [comment]
me too

**Comment by rgov** [comment]
Probably the patching is happening after the device has been enumerated the first time. Maybe there is a way I can force it to re-enumerate devices after unblocking. I haven't investigated it yet.

**Comment by ending0421** [comment]
Any progress now ? i have same issue.

**Comment by lmendezv** [comment]
I just wanted to add here in case others want to attempt it. I updated my firmware for the TB16 to the latest one on the DELL support site, 1.0.2, and everything is working correctly on 14.2. MacBook Pro (15-inch, 2017).

**Comment by rgov** [comment]
Can you link to the support site page? Can you confirm that video output works?

**Comment by rgov** [comment]
Cool. I'm going to close this issue and post your solution in #28.

**Comment by rgov** [comment]
@lmendezv Did you install the update from a Windows partition?

**Comment by lmendezv** [comment]
I installed it using a Dell XPS 15 9550 laptop running Windows 10 64-bit.
