### ISSUE TITLE
Restarted since the installation of Thunderbolt3Unblocker

### ISSUE THREAD

**Issue by i5ean** [rgov/Thunderbolt3Unblocker#31]
My Mac has been restarted since the installation of Thunderbolt3Unblocker, which has happened 7-8 times.
I want to know if it is related to the installation of Thunderbolt3Unblocker.
thanks.

[Kernel_2018-11-30-192306_SeandeMacBook-Pro.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/2634848/Kernel_2018-11-30-192306_SeandeMacBook-Pro.txt)
[Kernel_2018-11-13-223643_SeandeMacBook-Pro.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/2634849/Kernel_2018-11-13-223643_SeandeMacBook-Pro.txt)
[Kernel_2018-11-14-192011_SeandeMacBook-Pro.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/2634850/Kernel_2018-11-14-192011_SeandeMacBook-Pro.txt)
[Kernel_2018-11-15-191443_SeandeMacBook-Pro.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/2634851/Kernel_2018-11-15-191443_SeandeMacBook-Pro.txt)
[Kernel_2018-11-16-135300_SeandeMacBook-Pro.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/2634852/Kernel_2018-11-16-135300_SeandeMacBook-Pro.txt)
[Kernel_2018-11-16-184050_SeandeMacBook-Pro.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/2634853/Kernel_2018-11-16-184050_SeandeMacBook-Pro.txt)
[Kernel_2018-11-17-180403_SeandeMacBook-Pro.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/2634854/Kernel_2018-11-17-180403_SeandeMacBook-Pro.txt)
[Kernel_2018-11-22-154617_SeandeMacBook-Pro.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/2634855/Kernel_2018-11-22-154617_SeandeMacBook-Pro.txt)

**Comment by rgov** [comment]
At a glance it doesn’t seem related. Can you try uninstalling it and see if the crashes go away?

**Comment by i5ean** [comment]
I changed a mac and still restarted, and a new log was generated.
Restart occurs during sleep standby.
thank you

[panic-full-2018-12-24-065043.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/2708887/panic-full-2018-12-24-065043.txt)
[panic-full-2018-12-23-153831.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/2708888/panic-full-2018-12-23-153831.txt)

**Comment by rgov** [comment]
Both of these new panics are related to your Touch Bar, and are not related to Thunderbolt 3 Unblocker as far as I know. The ARM64 processor that powers your Touch Bar is crashing.

The latest panics are not the same as the ones you attached before, which for instance look like graphics subsystem crashes.

It is not likely that Thunderbolt 3 Unblocker is responsible for every kernel panic your system experiences. It might be related if it happens at the time you load T3U, or at the time you plug in a new Thunderbolt 3 device. It *might* happen on wake from sleep, but this doesn't seem related.
