### ISSUE TITLE
Wrong file permissions on kernel extension

### ISSUE THREAD

**Issue by romsweb** [rgov/Thunderbolt3Unblocker#32]
Hi Ryan,

before mojave,my HP elite dock thunderbolt 3 90 wats was working fine, since mojave, nothing work anymore, i try you last 28 september release and i got : 
MBP15-de-romain-1650:~ rpetitjean$ chmod -R /Library/Extensions/Thunderbolt3Unblocker.kext 
usage:	chmod [-fhv] [-R [-H | -L | -P]] [-a | +a | =a  [i][# [ n]]] mode|entry file ...
	chmod [-fhv] [-R [-H | -L | -P]] [-E | -C | -N | -i | -I] file ...
MBP15-de-romain-1650:~ rpetitjean$ sudo chmod -R 755 /Library/Extensions
Password:
MBP15-de-romain-1650:~ rpetitjean$ sudo sh -c 'chown -R root:wheel /Library/Extensions/Thunderbolt3Unblocker.kext && \
> kextcache -i / && \
> nvram -d t3u-incompatible && \
> kextload -b es.govost.ryan.Thunderbolt3Unblocker'
Kext with invalid signatured (-67050) allowed: <OSKext 0x7fb441a43930 [0x7fffa2c7f8f0]> { URL = "Thunderbolt3Unblocker.kext/ -- file:///Library/Extensions/", ID = "es.govost.ryan.Thunderbolt3Unblocker" }
Kext rejected due to improper filesystem permissions: <OSKext 0x7fb43eddbc60 [0x7fffa2c7f8f0]> { URL = "IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/", ID = "com.apple.iokit.IOThunderboltFamily" }
Rejecting invalid/inauthentic kext for bundle id com.apple.iokit.IOThunderboltFamily at location IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/.
Thunderbolt3Unblocker.kext - no compatible dependency found for com.apple.iokit.IOThunderboltFamily.
Thunderbolt3Unblocker.kext is missing dependencies (including anyway; dependencies may be available from elsewhere)
Rejecting invalid/inauthentic kext for bundle id com.apple.iokit.IOThunderboltFamily at location IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/.
AppleThunderboltDPInAdapter.kext - no compatible dependency found for com.apple.iokit.IOThunderboltFamily.
Rejecting invalid/inauthentic kext for bundle id com.apple.iokit.IOThunderboltFamily at location IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/.
AppleThunderboltDPAdapterFamily.kext - no compatible dependency found for com.apple.iokit.IOThunderboltFamily.
AppleThunderboltDPInAdapter.kext is missing dependencies (including anyway; dependencies may be available from elsewhere)
Rejecting invalid/inauthentic kext for bundle id com.apple.iokit.IOThunderboltFamily at location IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/.
AppleThunderboltDPAdapterFamily.kext - no compatible dependency found for com.apple.iokit.IOThunderboltFamily.
AppleThunderboltDPAdapterFamily.kext is missing dependencies (including anyway; dependencies may be available from elsewhere)
Rejecting invalid/inauthentic kext for bundle id com.apple.iokit.IOThunderboltFamily at location IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/.
AppleThunderboltDPOutAdapter.kext - no compatible dependency found for com.apple.iokit.IOThunderboltFamily.
Rejecting invalid/inauthentic kext for bundle id com.apple.iokit.IOThunderboltFamily at location IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/.
AppleThunderboltDPAdapterFamily.kext - no compatible dependency found for com.apple.iokit.IOThunderboltFamily.
AppleThunderboltDPOutAdapter.kext is missing dependencies (including anyway; dependencies may be available from elsewhere)
Rejecting invalid/inauthentic kext for bundle id com.apple.iokit.IOThunderboltFamily at location IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/.
AppleThunderboltIP.kext - no compatible dependency found for com.apple.iokit.IOThunderboltFamily.
AppleThunderboltIP.kext is missing dependencies (including anyway; dependencies may be available from elsewhere)
Rejecting invalid/inauthentic kext for bundle id com.apple.iokit.IOThunderboltFamily at location IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/.
AppleThunderboltEDMSink.kext - no compatible dependency found for com.apple.iokit.IOThunderboltFamily.
Rejecting invalid/inauthentic kext for bundle id com.apple.iokit.IOThunderboltFamily at location IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/.
AppleThunderboltDPOutAdapter.kext - no compatible dependency found for com.apple.iokit.IOThunderboltFamily.
Rejecting invalid/inauthentic kext for bundle id com.apple.iokit.IOThunderboltFamily at location IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/.
AppleThunderboltDPAdapterFamily.kext - no compatible dependency found for com.apple.iokit.IOThunderboltFamily.
AppleThunderboltEDMSink.kext is missing dependencies (including anyway; dependencies may be available from elsewhere)
Rejecting invalid/inauthentic kext for bundle id com.apple.iokit.IOThunderboltFamily at location IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/.
AppleThunderboltPCIUpAdapter.kext - no compatible dependency found for com.apple.iokit.IOThunderboltFamily.
Rejecting invalid/inauthentic kext for bundle id com.apple.iokit.IOThunderboltFamily at location IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/.
AppleThunderboltPCIDownAdapter.kext - no compatible dependency found for com.apple.iokit.IOThunderboltFamily.
AppleThunderboltPCIUpAdapter.kext is missing dependencies (including anyway; dependencies may be available from elsewhere)
Rejecting invalid/inauthentic kext for bundle id com.apple.iokit.IOThunderboltFamily at location IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/.
AppleThunderboltPCIDownAdapter.kext - no compatible dependency found for com.apple.iokit.IOThunderboltFamily.
AppleThunderboltPCIDownAdapter.kext is missing dependencies (including anyway; dependencies may be available from elsewhere)
IOThunderboltFamily.kext does not authenticate; omitting.
Rejecting invalid/inauthentic kext for bundle id com.apple.iokit.IOThunderboltFamily at location IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/.
AppleThunderboltUTDM.kext - no compatible dependency found for com.apple.iokit.IOThunderboltFamily.
AppleThunderboltUTDM.kext is missing dependencies (including anyway; dependencies may be available from elsewhere)
Rejecting invalid/inauthentic kext for bundle id com.apple.iokit.IOThunderboltFamily at location IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/.
AppleHPM.kext - no compatible dependency found for com.apple.iokit.IOThunderboltFamily.
AppleHPM.kext is missing dependencies (including anyway; dependencies may be available from elsewhere)
Rejecting invalid/inauthentic kext for bundle id com.apple.iokit.IOThunderboltFamily at location IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/.
AppleThunderboltNHI.kext - no compatible dependency found for com.apple.iokit.IOThunderboltFamily.
AppleThunderboltNHI.kext is missing dependencies (including anyway; dependencies may be available from elsewhere)
KernelCache ID: 3B0A15CC0D2B0AB7A39B8B9BAEB5C6B1
Kext rejected due to improper filesystem permissions: <OSKext 0x7ff81ea423f0 [0x7fffa2c7f8f0]> { URL = "IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/", ID = "com.apple.iokit.IOThunderboltFamily" }
Kext with invalid signatured (-67050) allowed: <OSKext 0x7ff821212cd0 [0x7fffa2c7f8f0]> { URL = "Thunderbolt3Unblocker.kext/ -- file:///Library/Extensions/", ID = "es.govost.ryan.Thunderbolt3Unblocker" }
es.govost.ryan.Thunderbolt3Unblocker failed to load - (libkern/kext) dependency load failed; check the system/kernel logs for errors or try kextutil(8).

can you please help me ? what else is possible ?

have a lovely day

**Comment by rgov** [comment]
Hi @romsweb, did you figure the problem out? It looks like some commands failed when you were trying to install the kext, which may have damaged the file permissions.

**Comment by romsweb** [comment]
Hi Ryan,
Yes I reinstalled Mojave (keeping files) works great!

Thanks

**Comment by rgov** [comment]
Ok great!
