### ISSUE TITLE
Dell TB15 partially working

### ISSUE THREAD

**Issue by peacechen** [rgov/Thunderbolt3Unblocker#33]
Thanks @rgov for sharing this project.

I am the unfortunate owner of the TB15 dock. Works well on a Dell laptop after some updates to both Windows and the TB15 firmware.
However it wouldn't work initially on a MacBook Pro with OSX 10.14.  It would charge, but no devices worked.

After using Thunderbolt3Unblocker, the Power Delivery, USB and Ethernet ports work, but DisplayPort/HDMI outputs do not.

Here's the spew from System Report.  The indentations didn't carry over, but it looks to be nested from Bus -> Cable -> Dock.
```
Thunderbolt Bus:

  Vendor Name:	Apple Inc.
  Device Name:	MacBook Pro
  UID:	0x0001AF6CC8926200
  Route String:	0
  Firmware Version:	39.2
  Domain UUID:	52A9C074-23F0-EB5F-9A4A-84FD16829106
  Port:
  Status:	No device connected
  Link Status:	0x7
  Speed:	Up to 40 Gb/s x1
  Current Link Width:	0x1
  Receptacle:	2
  Link Controller Firmware Version:	0.38.0
  Port:
  Status:	Device connected
  Link Status:	0x2
  Speed:	Up to 40 Gb/s x1
  Current Link Width:	0x2
  Receptacle:	1
  Link Controller Firmware Version:	0.38.0

Dell Thunderbolt Cable:

  Vendor Name:	Dell
  Device Name:	Dell Thunderbolt Cable
  Vendor ID:	0xD4
  Device ID:	0xB051
  Device Revision:	0x1
  UID:	0x8086A34344E02510
  Route String:	3
  Firmware Version:	15.15
  Port (Upstream):
  Status:	Device connected
  Link Status:	0x2
  Speed:	Up to 40 Gb/s x1
  Current Link Width:	0x2
  Link Controller Firmware Version:	0.24.0
  Port:
  Status:	Device connected
  Link Status:	0x2
  Speed:	Up to 40 Gb/s x1
  Current Link Width:	0x2
  Link Controller Firmware Version:	0.24.0

Dell Thunderbolt Dock:

  Vendor Name:	Dell
  Device Name:	Dell Thunderbolt Dock
  Vendor ID:	0xD4
  Device ID:	0xB054
  Device Revision:	0x1
  UID:	0x8086A321A4B28410
  Route String:	303
  Firmware Version:	15.15
  Port (Upstream):
  Status:	Device connected
  Link Status:	0x2
  Speed:	Up to 40 Gb/s x1
  Current Link Width:	0x2
  Link Controller Firmware Version:	0.24.0
  Port:
  Status:	No device connected
  Link Status:	0x7
  Speed:	Up to 40 Gb/s x1
  Current Link Width:	0x1
  Link Controller Firmware Version:	0.24.0
```

**Comment by rgov** [comment]
It looks like T3U is working fine—it allows the rest of the system to "see" that the TB15 is plugged in. However, once that is done, T3U's job is over. It does not know anything about video output; that's the responsibility of some other driver. Unfortunately, it seems like you don't have a driver that can deal with the video ports on the TB15.

Please see also the thread about the TB16. I don't have either of these devices and don't know anything about them, unfortunately. https://github.com/rgov/Thunderbolt3Unblocker/issues/28
