### ISSUE TITLE
10.4.4 faild to load shows "authentication failure (file ownership/permissions)"

### ISSUE THREAD

**Issue by tyhunter** [rgov/Thunderbolt3Unblocker#36]
Hi Ryan ,  when I try to use your kext to unlock thunderbolt3 for HP Zbook TB3 Dock
I found some problem make it failed to load (had already disable SIP)
the wrong code seems the file permission is wrong and couldn't change by su

> ➜  ~ sudo sh -c 'chown -R root:wheel /Library/Extensions/Thunderbolt3Unblocker.kext && \
quote> kextcache -i / && \
quote> nvram -d t3u-incompatible && \
quote> kextload -b es.govost.ryan.Thunderbolt3Unblocker'
KernelCache ID: 7B9F5DE8145A59078C9F0578C406200A
Kext rejected due to improper filesystem permissions: <OSKext 0x7ff5744c56c0 [0x7fff859b48f0]> { URL = "Thunderbolt3Unblocker.kext/ -- file:///System/Library/Extensions/", ID = "es.govost.ryan.Thunderbolt3Unblocker" }
Kext rejected due to improper filesystem permissions: <OSKext 0x7ff571f6a500 [0x7fff859b48f0]> { URL = "Thunderbolt3Unblocker.kext/ -- file:///Library/Extensions/", ID = "es.govost.ryan.Thunderbolt3Unblocker" }
es.govost.ryan.Thunderbolt3Unblocker failed to load - (libkern/kext) authentication failure (file ownership/permissions); check the system/kernel logs for errors or try kextutil(8).

and the sudo kextutil shows 

>  ➜  ~ sudo kextutil /Library/Extensions/Thunderbolt3Unblocker.kext
Kext rejected due to improper filesystem permissions: <OSKext 0x7fbd5250cbe0 [0x7fff859b48f0]> { URL = "file:///Library/Extensions/Thunderbolt3Unblocker.kext/", ID = "es.govost.ryan.Thunderbolt3Unblocker" }
Code Signing Failure: code signature is invalid
Authentication Failures: 
    File owner/permissions are incorrect (must be root:wheel, nonwritable by group/other): 
        /Library/Extensions/Thunderbolt3Unblocker.kext
        Contents
        _CodeSignature
        CodeResources
        MacOS
        Thunderbolt3Unblocker
        Resources
        LICENSE.md
        Info.plist
Diagnostics for /Library/Extensions/Thunderbolt3Unblocker.kext:
Authentication Failures: 
    File owner/permissions are incorrect (must be root:wheel, nonwritable by group/other): 
        /Library/Extensions/Thunderbolt3Unblocker.kext
        Contents
        _CodeSignature
        CodeResources
        MacOS
        Thunderbolt3Unblocker
        Resources
        LICENSE.md
        Info.plist

<

Thank you so much

**Comment by tyhunter** [comment]
I try to use

> sudo chmod -R 755 Thunderbolt3Unblocker.kext && sudo chown -R root:wheel Thunderbolt3Unblocker.kext

Seems it can load now

**Comment by rgov** [comment]
> File owner/permissions are incorrect (must be root:wheel, nonwritable by group/other):

Looks like that's the problem. Thanks.
