### ISSUE TITLE
Can Support Mojave 10.4.5?

### ISSUE THREAD

**Issue by tyhunter** [rgov/Thunderbolt3Unblocker#38]
Today Apple Release the Mojave 10.4.5
Had anyone tries to update 10.4.5 and the Thunderbolt3Unblocker still working?

**Comment by dqhoang** [comment]
Doesn't seem to work on my machine. Recently updated to 10.14.5

**Comment by tyhunter** [comment]
> Doesn't seem to work on my machine. Recently updated to 10.14.5
> 
> `Kext with invalid signatured (-67050) allowed: <OSKext 0x7f8b5d9234d0 [0x7fff938858e0]> { URL = "file:///Library/Extensions/Thunderbolt3Unblocker.kext/", ID = "es.govost.ryan.Thunderbolt3Unblocker" }`

Had you tried kextload & kextunload by that issue >https://github.com/rgov/Thunderbolt3Unblocker/issues/37

**Comment by rgov** [comment]
@dqhoang That is not an error message. That specifically says that loading the kext was **allowed**.

**Comment by tyhunter** [comment]
@dqhoang @rgov  the Update has automatically installed in my lunchtime, so when the system auto reboot and finished the update, I found the SIP is auto enable and I had to disable it in the recovery mode. Then enter the " sudo kextload Thunderbolt3Unblocker.kext " in the terminal, the kext is successfully loaded
