### ISSUE TITLE
run `csrutil enable --without kext`

### ISSUE THREAD

**Issue by loretoparisi** [rgov/Thunderbolt3Unblocker#4]
When executing `csrutil enable --without kext` I get

```
$ csrutil enable --without kext
csrutil: requesting an unsupported configuration. This is likely to break in the future and leave your machine in an unknown state.
csrutil: failed to modify system integrity configuration. This tool needs to be executed from the Recovery OS.
```

So shall I need to boot from a Recovery OS? If so, is it ok to do like

```
https://support.apple.com/en-us/HT204904 covers normal recovery
hold Command+r+s to boot into Single User Recovery Mode.
```

Thank you!

**Comment by rgov** [comment]
Yes, for security purposes you can only change SIP settings from the Recovery HD. This prevents malware from being able to change it.

I think if you have signed the kext using your own developer ID you might not need to.

**Comment by loretoparisi** [comment]
@rgov uhm so when building with XCode, I'm using my Mac Developer plus my Apple developer account. So it should not be needed then?

**Comment by loretoparisi** [comment]
@rgov I have compiled with my personal account (not company account) and this time I get an error when trying to load it:

```
$ sudo kextload Thunderbolt3Unblocker.kext
/Users/loretoparisi/Library/Developer/Xcode/DerivedData/Thunderbolt3Unblocker-eukqoodzvjlnlhaathavcwpkifmy/Build/Products/Debug/Thunderbolt3Unblocker.kext failed to load - (libkern/kext) not loadable (reason unspecified); check the system/kernel logs for errors or try kextutil(8).
```

**Comment by rgov** [comment]
I might use Console.app instead of the command line, or `dmesg`, immediately after trying to load and it should tell you the error. For instance, I don't know if the failure to load message comes from the kernel or from `kextd` or similar.

**Comment by loretoparisi** [comment]
@rgov ah so! got the errors!!!

```
kxld[es.govost.ryan.Thunderbolt3Unblocker]: The following symbols are unresolved for this kext:
kxld[es.govost.ryan.Thunderbolt3Unblocker]: 	___memcpy_chk
kxld[es.govost.ryan.Thunderbolt3Unblocker]: 	___memmove_chk
kxld[es.govost.ryan.Thunderbolt3Unblocker]: 	___memset_chk
Can't load kext es.govost.ryan.Thunderbolt3Unblocker - link failed.
Failed to load executable for kext es.govost.ryan.Thunderbolt3Unblocker.
Kext es.govost.ryan.Thunderbolt3Unblocker failed to load (0xdc008016).
Failed to load kext es.govost.ryan.Thunderbolt3Unblocker (error 0xdc008016).
```

**Comment by likaci** [comment]
same error with @loretoparisi

**Comment by rgov** [comment]
Thanks. I'm surprised they're not offered in xnu. Can you tell me the version of the kernel you are using?

**Comment by loretoparisi** [comment]
@rgov `Xcode Version 9.2 (9C40b)` and 

```
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1212
```

**Comment by rgov** [comment]
Can you add `-D_FORTIFY_SOURCE=0` to `OTHER_C_FLAGS` and see if that resolves the issue? Note that your system is a major release behind.

**Comment by shinvou** [comment]
@loretoparisi Compile it with Xcode 8.x.x and your problems are gone. ;)

**Comment by loretoparisi** [comment]
@rgov I have added, but I get

```
[loretoparisi@:mbploreto Thunderbolt3Unblocker]$ sudo kextutil Thunderbolt3Unblocker.kext
Diagnostics for Thunderbolt3Unblocker.kext:
Code Signing Failure: code signature is invalid
kext-dev-mode allowing invalid signature -67050 0xFFFFFFFFFFFEFA16 for kext "Thunderbolt3Unblocker.kext"
kext signature failure override allowing invalid signature -67050 0xFFFFFFFFFFFEFA16 for kext "/Users/loretoparisi/Desktop/Thunderbolt3Unblocker/Thunderbolt3Unblocker.kext"
(kernel) kxld[com.musixmatch.Thunderbolt3Unblocker]: The following symbols are unresolved for this kext:
(kernel) kxld[com.musixmatch.Thunderbolt3Unblocker]: 	___memcpy_chk
(kernel) kxld[com.musixmatch.Thunderbolt3Unblocker]: 	___memset_chk
(kernel) Can't load kext com.musixmatch.Thunderbolt3Unblocker - link failed.
(kernel) Failed to load executable for kext com.musixmatch.Thunderbolt3Unblocker.
(kernel) Kext com.musixmatch.Thunderbolt3Unblocker failed to load (0xdc008016).
(kernel) Failed to load kext com.musixmatch.Thunderbolt3Unblocker (error 0xdc008016).
Failed to load Thunderbolt3Unblocker.kext - (libkern/kext) link error.
Check library declarations for your kext with kextlibs(8).
```

<img width="971" alt="schermata 2018-03-18 alle 17 13 40" src="https://user-images.githubusercontent.com/163333/37568022-bdb716a4-2acf-11e8-81f0-b3a85f04853d.png">

So if there is no other option, I have to go back to 8...but it's not clear to my why?

**Comment by shinvou** [comment]
@loretoparisi 

> [...] I have to go back to 8...but it's not clear to my why?

Because this version of Xcode includes the 10.12 SDK, which is the SDK for the system you are running. I don't know the exact reason why Xcode fails to link this stuff with newer SDK than the system is running, but it does and that's why you need to use an older Xcode (SDK).

**Comment by loretoparisi** [comment]
@shinvou @rgov Hello guys,
so I have downgraded to Xcode `Version 8.3.3 (8E3004b)` but I'm still getting the same error:

```
[loretoparisi@:mbploreto Thunderbolt3Unblocker]$ sudo kextutil Thunderbolt3Unblocker.kext
Diagnostics for Thunderbolt3Unblocker.kext:
Code Signing Failure: code signature is invalid
kext-dev-mode allowing invalid signature -67050 0xFFFFFFFFFFFEFA16 for kext "Thunderbolt3Unblocker.kext"
kext signature failure override allowing invalid signature -67050 0xFFFFFFFFFFFEFA16 for kext "/Users/loretoparisi/Desktop/Thunderbolt3Unblocker/Thunderbolt3Unblocker.kext"
(kernel) kxld[com.musixmatch.Thunderbolt3Unblocker]: The following symbols are unresolved for this kext:
(kernel) kxld[com.musixmatch.Thunderbolt3Unblocker]: 	___memcpy_chk
(kernel) kxld[com.musixmatch.Thunderbolt3Unblocker]: 	___memset_chk
(kernel) Can't load kext com.musixmatch.Thunderbolt3Unblocker - link failed.
(kernel) Failed to load executable for kext com.musixmatch.Thunderbolt3Unblocker.
(kernel) Kext com.musixmatch.Thunderbolt3Unblocker failed to load (0xdc008016).
(kernel) Failed to load kext com.musixmatch.Thunderbolt3Unblocker (error 0xdc008016).
Failed to load Thunderbolt3Unblocker.kext - (libkern/kext) link error.
Check library declarations for your kext with kextlibs(8).
```

**Comment by rgov** [comment]
Define a function in one of the C files named

```
void *_memcpy_chk(void *dst, void *src, size_t n) { return memcpy(dst, src, n); }
void *_memset_chk(void *b, int c, size_t len) { return memset(b, c, len); }
```

**Comment by loretoparisi** [comment]
@rgov thanks! Is it ok in the `Thunderbolt3Unblocker.c`?

**Comment by rgov** [comment]
I suspect so. It's just a theory for how to fix it.

**Comment by loretoparisi** [comment]
@rgov uhm...my suspect is that I'm getting this

```
For all architectures:
    com.apple.iokit.IOThunderboltFamily = 6.5.7
    com.apple.kpi.libkern = 16.7
    com.apple.kpi.mach = 16.7

For x86_64:
    4 symbols not found in any library kext.
```

so as the Mach symbols were not there or I'm compiling against a bad version of the SDK.

**Comment by rgov** [comment]
Does it list the 4 symbols not found?

**Comment by loretoparisi** [comment]
@rgov Here you are!!!

```
$ sudo kextlibs -xml -undef Thunderbolt3Unblocker.kext
	<key>OSBundleLibraries</key>
	<dict>
		<key>com.apple.iokit.IOThunderboltFamily</key>
		<string>6.5.7</string>
		<key>com.apple.kpi.libkern</key>
		<string>16.7</string>
		<key>com.apple.kpi.mach</key>
		<string>16.7</string>
	</dict>

For x86_64:
    4 symbols not found in any library kext:
	___memcpy_chk
	_get_task_map
	_vm_protect
	___memset_chk
```

**Comment by rgov** [comment]
`get_task_map` and `vm_protect` are crucial and if they are missing, the kext cannot work. It's possible there is another way to access them if you wanted to put the effort into researching it, but I recommend that you upgrade to a newer version of macOS.

**Comment by loretoparisi** [comment]
@rgov ok thank you I'm going to upgrade to `macOS 10.13` then!

**Comment by ryanwmarsh** [comment]
I'm on 10.13.4 Beta (17E182a) and I too get 

```
sudo kextlibs -xml -undef Thunderbolt3Unblocker.kext
	<key>OSBundleLibraries</key>
	<dict>
		<key>com.apple.iokit.IOThunderboltFamily</key>
		<string>6.7.8</string>
		<key>com.apple.kpi.libkern</key>
		<string>17.5</string>
		<key>com.apple.kpi.mach</key>
		<string>17.5</string>
	</dict>

For x86_64:
    2 symbols not found in any library kext:
	_get_task_map
	_vm_protect
```

**Comment by rgov** [comment]
Let's start a separate issue, since this doesn't have anything to do with code signing at this point. I expect 10.13.4 will be released imminently and I'll update the kext shortly thereafter, but I hope it's easy to resolve.

**Comment by ryanwmarsh** [comment]
@rgov Ok cool thanks and thank you very much for responding so quickly!

**Comment by loretoparisi** [comment]
@rgov and thank you from me again...hopefully I will be able to run my Nvidia GPU son 💯

**Comment by rgov** [comment]
macOS 10.13.4 was released today and I do not see any compatibility issues. If you are still having trouble getting it to load, please file a new issue.

**Comment by loretoparisi** [comment]
@rgov thanks I will give a try after Easter 👍
