### ISSUE TITLE
Could work on MacOS Catalina(10.15 Beta 19A471t) But Installaion need to be done under mojave.

### ISSUE THREAD

**Issue by Oyami-Srk** [rgov/Thunderbolt3Unblocker#40]
Just a report.  I have clean installed Beta Catalina, and after that, the installation guide works fine(kext allowed) but tb3 not detected. **Works fine but freshly installing not**

**Comment by Oyami-Srk** [comment]
@tyhunter Dell‘s TB3 Dock. Everything works fine.

**Comment by Oyami-Srk** [comment]
after a clean install, the TB3Unblocker's installation guide is no longer usable.
Perhaps the Catalina has a more step to enable 3rd-part kext?
here is the kextutil result:
`root@SRK-MBP Documents # kextutil -v -b es.govost.ryan.Thunderbolt3Unblocker
Defaulting to kernel file '/System/Library/Kernels/kernel'
Kext with invalid signature (-67050) allowed: <OSKext 0x7fc18f409bc0 [0x7fff938947d0]> { URL = "file:///Library/Extensions/Thunderbolt3Unblocker.kext/", ID = "es.govost.ryan.Thunderbolt3Unblocker" }
Reading migration.plist (allowBundleIDs:0, cdhashArrayRef:0)
WARNING: Did not find migration.plist - some kexts may fail to load
Could not find <OSKext 0x7fc18f409bc0 [0x7fff938947d0]> { URL = "file:///Library/Extensions/Thunderbolt3Unblocker.kext/", ID = "es.govost.ryan.Thunderbolt3Unblocker" } (bundleID:es.govost.ryan.Thunderbolt3Unblocker cdhash:<CFData 0x7fc18f4a4610 [0x7fff938947d0]>{length = 20, capacity = 20, bytes = 0x0f54e2c700aba1fe4b7205a07a942bd607a0de84}) in list of 0/10 allowed 3rd party kexts
Allowing 3rd party kext w/o reboot: <OSKext 0x7fc18f409bc0 [0x7fff938947d0]> { URL = "file:///Library/Extensions/Thunderbolt3Unblocker.kext/", ID = "es.govost.ryan.Thunderbolt3Unblocker" }
Kext with invalid signature (-67054) allowed: <OSKext 0x7fc18f632720 [0x7fff938947d0]> { URL = "file:///System/Library/Extensions/IOThunderboltFamily.kext/", ID = "com.apple.iokit.IOThunderboltFamily" }
Code Signing Failure: code signature is invalid
/Library/Extensions/Thunderbolt3Unblocker.kext appears to be loadable (not including linkage for on-disk libraries).
Loading /Library/Extensions/Thunderbolt3Unblocker.kext.
/Library/Extensions/Thunderbolt3Unblocker.kext successfully loaded (or already loaded).
root@SRK-MBP Documents # 
`

**Comment by rgov** [comment]
@Oyami-Srk Can you explain why you think it doesn't work? There is no error in the above output.

**Comment by Oyami-Srk** [comment]
@rgov I do a clean install again, and follow the instruction on the release page to make sure kext is loaded. The result is like above. Kext seems to be loaded, but since my tb3 docker cannot be detected by the OS, I think that Kext may be unfunctional. Is any other log I can provide? I hope that just a bug in beta.

**Comment by rgov** [comment]
Apple is tightening restrictions on kernel extensions and it would not surprise me if this one is blocked at some point. 

I have not yet installed the beta. I will try it at some point.

**Comment by exeliser** [comment]
Kext with invalid signature (-67062) allowed: <OSKext 0x7fd4f46da780 [0x7fff925f77d0]> { URL = "file:///Library/Extensions/HoRNDIS.kext/", ID = "com.joshuawise.kexts.HoRNDIS" }
Kext with invalid signature (-67050) allowed: <OSKext 0x7fd4f46d7b10 [0x7fff925f77d0]> { URL = "file:///Library/Extensions/Thunderbolt3Unblocker.kext/", ID = "es.govost.ryan.Thunderbolt3Unblocker" }

This is what I get when installing it on 10.15

**Comment by exeliser** [comment]
To add I installed it and used it on mojave then I installed cathalina and it completely didn't function anymore. Not even my mouse is getting power. Tried reinstalling but got that ^

**Comment by rgov** [comment]
Please read the Troubleshooting guide on the wiki. Thanks.

**Comment by rgov** [comment]
Closing in favor of #42. Please follow the Troubleshooting guide when filing issues. Thanks.
