### ISSUE TITLE
Built successful but I can not find the created kext... 

### ISSUE THREAD

**Issue by Cdartois** [rgov/Thunderbolt3Unblocker#41]

**Comment by Cdartois** [comment]
Running macosx 10.14.5 (18F203), the software seems to compile but I can not find the .kext generated, hence can not perform the command :

Cyrils-MacBook-Pro:Thunderbolt3Unblocker cyril$ sudo chown -R root:wheel Thunderbolt3Unblocker.kext
Password:
chown: Thunderbolt3Unblocker.kext: No such file or directory

Any idea what I should do ?

**Comment by rgov** [comment]
If you aren’t making modifications I suggest you download a prebuilt release. 

Otherwise the build log will tell you the directory it placed the build products in.
