### ISSUE TITLE
universal audio Apollo 8chan

### ISSUE THREAD

**Issue by soundproofmedia** [rgov/Thunderbolt3Unblocker#43]
[t3u-diagnose.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/3388771/t3u-diagnose.txt)

Hi There,
I am trying to use this kext to enable thunderbolt on my Mac Pro 5. 1 to use with a Universal Audio Apollo device, any ideas why we might be having trouble. 

Any help greatly appreciated,

All the best, 

Adam

**Comment by rgov** [comment]
Please explain what is not working. Is it crashing? Device is not showing up?

The diagnostics file says that you don’t have a Thunderbolt driver loaded. And when I look up the specs for the MacPro5,1, it doesn’t have any Thunderbolt ports. So how are you plugging it in at all?

Which Apollo model are you trying to use?

**Comment by soundproofmedia** [comment]
I'm sorry, I think I misunderstood the purpose of the script. I have
installed a Gigabyte Titan Ridge thunderbolt card. My hope was that your
script would enable the thunderbolt drivers built in to the Mojave OS.
Do you think there would be a way of modifying the code to enable it?

It seems possible to do it by booting to windows installing drivers and
then warm booting to osx, which keeps the drivers active and enables use
with Mac 5,1.

Thanks for the speedy response! :)

**Comment by rgov** [comment]
I see. Yes, it looks like you will need to take a different approach: https://egpu.io/forums/builds/thunderbolt-3-on-amd-x399-threadripper-rtx-208032gbps-tb3-razer-core-x-win10-1803-itsage/

This project helps you if Apple has blacklisted a device. But that doesn't seem to be the case here. Good luck.
