### ISSUE TITLE
WD15

### ISSUE THREAD

**Issue by luco** [rgov/Thunderbolt3Unblocker#44]
Guys, sorry it's not a bug or issue. O maybe is. I haven't installed this packaged and I'm asking if should I do it. I kinda need some information first.

I have a WD15 attached to my MB2018 on Mojave. It works perfectly most of the time. mDP works fine, Ethernet works fine, even the battery charge works fine.

However, after some time, it starts throwing SSL erros on the ethernet port. I gotta to reboot it to make it work again. Also, sometimes it drains my battery life so fast (or stops providing power), resulting in a 4%~ battery percentage quickly.

I have to reboot it several times to get it working.

Would this package solve this issues or should I perform a firmware update?

Thanks!

**Comment by rgov** [comment]
Hi @luco, these issues cannot be related to this kernel extension. It does not affect battery drainage or SSL errors.
