### ISSUE TITLE
when building in xcode i got error

### ISSUE THREAD

**Issue by ilovefood2** [rgov/Thunderbolt3Unblocker#46]
does anyone know how to fix it ?
im using 10.14.6
xcode 10.3

thanks
![image](https://user-images.githubusercontent.com/4293869/64846279-4775cc80-d5da-11e9-871f-bde2d7d38054.png)

**Comment by ilovefood2** [comment]
update: i changed it to #include <../msvc/ZydisExportConfig.h> this error is gone however more errors came up 
/Users/kelvin/Library/Mobile Documents/com~apple~CloudDocs/AppleProjects/Thunderbolt3Unblocker/xnu_override/zydis/include/Zydis/MetaInfo.h:79:1: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes

any idea?

**Comment by ilovefood2** [comment]
one error after another, it seems i have got lots issues just to compiling it...

```
Libtool /Users/kelvin/Library/Developer/Xcode/DerivedData/Thunderbolt3Unblocker-gerlbhkplgckkpdmubbqloirtkkb/Build/Products/Debug/libxnu_override.a normal x86_64
    cd "/Users/kelvin/Library/Mobile Documents/com~apple~CloudDocs/AppleProjects/Thunderbolt3Unblocker"
    export MACOSX_DEPLOYMENT_TARGET=10.13
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -arch_only x86_64 -D -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -L/Users/kelvin/Library/Developer/Xcode/DerivedData/Thunderbolt3Unblocker-gerlbhkplgckkpdmubbqloirtkkb/Build/Products/Debug -L/Users/kelvin/Library/Developer/Xcode/DerivedData/Thunderbolt3Unblocker-gerlbhkplgckkpdmubbqloirtkkb/Build/Products/Debug/zydis -filelist /Users/kelvin/Library/Developer/Xcode/DerivedData/Thunderbolt3Unblocker-gerlbhkplgckkpdmubbqloirtkkb/Build/Intermediates.noindex/Thunderbolt3Unblocker.build/Debug/xnu_override.build/Objects-normal/x86_64/xnu_override.LinkFileList -lZydis -o /Users/kelvin/Library/Developer/Xcode/DerivedData/Thunderbolt3Unblocker-gerlbhkplgckkpdmubbqloirtkkb/Build/Products/Debug/libxnu_override.a

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lZydis
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lZydis is not an object file (not allowed in a library)

```

**Comment by rgov** [comment]
Hi @ilovefood2, please do a clean build and post the build log to gist.github.com.

Did you follow the build instructions completely? All of your issues involve the Zydis dependency. You should *not* change the include of `ZydisExportConfig.h` to use the one you found (it is for the Microsoft Visual C++ compiler), this file should have been generated during build.

**Comment by ilovefood2** [comment]
I ended up with downloading pre-compiled latest release 
and ran the following 

```
sudo sh -c 'chown -R root:wheel /Library/Extensions/Thunderbolt3Unblocker.kext && \
> chmod -R g-w,o-w /Library/Extensions/Thunderbolt3Unblocker.kext && \
> kextcache -i / && \
> nvram -d t3u-incompatible && \
> kextload -b es.govost.ryan.Thunderbolt3Unblocker'
```
and I got following msg, it seems kext has been successfully loaded
```
KernelCache ID: 6DB00079C10F1334BA40A850B57213B0
Kext with invalid signatured (-67050) allowed: <OSKext 0x7fc3341bffd0 [0x7fffa3b838e0]> { URL = "file:///Library/Extensions/Thunderbolt3Unblocker.kext/", ID = "es.govost.ryan.Thunderbolt3Unblocker" }
```

but somehow my MacBook Pro still does not recognize USB ports on TB16, I tried with all USB ports on dock with a mouse, but none is working. in system profile, it shows correct info though. 

any suggestions? 

<img width="355" alt="Screen Shot 2019-09-13 at 11 40 46 AM" src="https://user-images.githubusercontent.com/4293869/64875566-6183cf00-d61b-11e9-933f-ab31317a8566.png">

**Comment by rgov** [comment]
Please read the [Troubleshooting guide](https://github.com/rgov/Thunderbolt3Unblocker/wiki/Troubleshooting), which has information about the TB16. It looks like Thunderbolt3Unblocker is working for you.

**Comment by ilovefood2** [comment]
I read about TB16, but nothing seems related. 
and I removed thunderbolt3unlocker, it still shows supported somehow...

**Comment by rgov** [comment]
I do not have a TB16 so I cannot help, but all Thunderbolt 3 Unblocker does is remove the word "Unsupported" from System Profile and allow drivers to load for a device. By all appearances T3U is working fine, so there must be some other issue.

Like the Troubleshooting guide says, there is a command to generate a diagnostics file you can use when filing bugs, which will help me see whether T3U is broken somehow.

You can post clear steps that you've followed in the TB16 thread and maybe someone who has one can help.

**Comment by rgov** [comment]
Are you running on macOS Catalina?

**Comment by ilovefood2** [comment]
No, I’m on 10.14.6 Mojave
