### ISSUE TITLE
DELL TB16 is not detected. Two monitors work as mirrored.

### ISSUE THREAD

**Issue by kozaksv** [rgov/Thunderbolt3Unblocker#48]
I've tried to upgrade TB16 from dell Latitude 7300 with thunderbolt but got an error "reading asmedia usb 3.0 host controller firmware failed". 
After that I've upgraded it from Ubuntu using FWUPD to firmware version 3.12.002. 
Now I got two monitors worked as mirrors and plus my laptop monitor on MacOS Mojave 10.14.6 . But on Ubuntu or Windows they extend my desktop correctly and I got three separated monitors.

---
Unlocker is loaded
![image](https://user-images.githubusercontent.com/776308/68018009-ba2d2b00-fca0-11e9-97d9-c4a1896fc3cc.png)
But there are no devices connected.
![image](https://user-images.githubusercontent.com/776308/68018044-d16c1880-fca0-11e9-8682-b69a8c4e1adf.png)

I attached t3u-diagnose.txt

[t3u-diagnose.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/3797421/t3u-diagnose.txt)

**Comment by rgov** [comment]
It looks like macOS cannot even see the Thunderbolt device. This tool only
helps if it can see the device and the device normally says "Unsupported"
in System Profile. I don't know why the system cannot see the Thunderbolt
device in the first place, and I do not have this device to test with,
sorry.
