### ISSUE TITLE
enable SIP after running the script

### ISSUE THREAD

**Issue by sjxnwnqksnrlq** [rgov/Thunderbolt3Unblocker#49]
After I ran the script listed in the repo, I restart to recovery OS to enable SIP again. Unfortunately, when I go back to macOS again, I can't load the Unblocker kext again. So does the kext need SIP disabled all the time when I want to use the unsupported Thunderbolt 3 peripherals?
My OS is macOS Catalina 10.15.1 and the script below is copied from the release page.
[https://github.com/rgov/Thunderbolt3Unblocker/releases](url)
> sudo sh -c 'chown -R root:wheel /Library/Extensions/Thunderbolt3Unblocker.kext && \
> chmod -R g-w,o-w /Library/Extensions/Thunderbolt3Unblocker.kext && \
> kextcache -i / && \
> nvram -d t3u-incompatible && \
> kextload -b es.govost.ryan.Thunderbolt3Unblocker'

**Comment by rgov** [comment]
Yes, SIP needs to remain disabled. If you follow the instructions, *most* of SIP remains enabled so you still get a good amount of protection.

**Comment by sjxnwnqksnrlq** [comment]
> Yes, SIP needs to remain disabled. If you follow the instructions, *most* of SIP remains enabled so you still get a good amount of protection.
> […](#)

Thanks! But after I type the enabling command with "--without kext", it says "requesting an unsupported configuration, This is likely to break in the future and leave your machine in an unknown state."
Could you tell me what the risk is?

**Comment by rgov** [comment]
It sounds like you are worried about ensuring the stability of your machine, in which case you should be aware that, while I have never attributed a crash to a released version and I have developed some safety features to prevent them, this tool is meddling with low-level system internals to enable hardware that Apple has deliberately disabled. So I would not use it on anything mission critical and *expect* it to blow things up but be pleasantly surprised that it doesn't.

Regarding your question: The risk is low. It would be that Apple releases a new macOS update some day that removes the `--without kext` option. You would be forced to change SIP to either completely on (and Thunderbolt 3 Unblocker will not work anymore), or completely off (and you will not get some of the security protections that SIP offers). It is very unlikely that it would cause any data loss or anything like that.

Put another way: the risk is far higher that T3U itself will cause problems for you then setting SIP to an unsupported configuration. But it's very easy to uninstall T3U or reset SIP from the recovery OS.
