### ISSUE TITLE
Can't build xcode project

### ISSUE THREAD

**Issue by raphax** [rgov/Thunderbolt3Unblocker#5]
Hi, i don't know what I'm doing wrong, but I can't build with xcode.
I got this error:

<img width="862" alt="captura de tela 2018-03-31 as 02 43 06" src="https://user-images.githubusercontent.com/14810478/38160074-430a7f00-348d-11e8-9101-0c988fc3c920.png">

**Comment by rgov** [comment]
Hi, please run `git submodule update --init --recursive` inside the project directory and try again.

The build script is supposed to [do this for you](https://github.com/rgov/Thunderbolt3Unblocker/blob/master/xnu_override/build_zydis.sh#L27), I'm not sure why it didn't.

**Comment by rgov** [comment]
Thanks for your report. I've improved the build script so that this step is done automatically.

**Comment by raphax** [comment]
Perfect! Thankyou... Now the build was succeeded, but I can't find the patched kext (Thunderbolt3Unblocker.kext)... I'm new with Mac development yet... Sorry about that...
