### ISSUE TITLE
Does not survive a reboot

### ISSUE THREAD

**Issue by bcompono** [rgov/Thunderbolt3Unblocker#50]
Applied file and commands, unplugged and plugged Akitio Thunder3 Quad enclosure, worked great.  Rebooted, back to square one.  Applied commands, unplugged and plugged, worked great.

Is this expected behavior?

**Comment by rgov** [comment]
Please follow the [Troubleshooting Guide](https://github.com/rgov/Thunderbolt3Unblocker/wiki/Troubleshooting), which was also requested in the issue template when you created your issue, and include the diagnostics file.

The extension will only be loaded automatically if it is installed in /Library/Extensions.

**Comment by bcompono** [comment]
[t3u-diagnose.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/3875580/t3u-diagnose.txt)

Diagnostic file attached.  The file is in /Library/Extensions.  I half expected a reply that it was expected behavior, thus no diagnostic file.

**Comment by bcompono** [comment]
[t3u-diagnose.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/3875842/t3u-diagnose.txt)


After reboot

**Comment by rgov** [comment]
After rebooting, without doing anything else, please run `kextstat` and include the output.

Please also try unplugging the device and plugging it back in after reboot, without reloading the extension.

**Comment by bcompono** [comment]
After a reboot when I unplug the thunderbolt cable from the enclosure side and plug it back in the enclosure is recognized, and it's disks and the unsupported note is gone from the system report.  I've attached the kextstat command output.  I should also note that I have to connect my Mac Pro 6.1 to the AKiTo enclosure using the Apple TB2 to TB3 adapter.

[kextstatoutput.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/3875970/kextstatoutput.txt)

**Comment by rgov** [comment]
Great. So it seems that perhaps the Thunderbolt3Unblocker extension is loading, but after the device has already been rejected. Replugging it clears the rejection. 

At the moment I don’t have a solution to force the devices to be re-enumerated. But at least you don’t need to do anything other than plug in a cable.

**Comment by bcompono** [comment]
Good to know.  I'm just thankful it works at all.  I had hoped to be able to boot from it but that's out, but I have a "toaster" TB2 dock that will work for that.  Thanks for unbreaking something Apple broke!  I'm sure they have their reasons, but their reasons are not necessarily the same as mine.  :)
