### ISSUE TITLE
Not loading on macOS 10.13.5

### ISSUE THREAD

**Issue by langxiaopiao030** [rgov/Thunderbolt3Unblocker#51]
Not loaded.
t3u-incompatible	17.6.0
System Integrity Protection status: disabled.
Software:

    System Software Overview:

      System Version: macOS 10.13.5 (17F77)
      Kernel Version: Darwin 17.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: God的MacBook Pro
      User Name: God (god)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Disabled
      Time since boot: 15 minutes

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro14,3
      Processor Name: Intel Core i7
      Processor Speed: 2.8 GHz
      Number of Processors: 1
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache: 6 MB
      Memory: 16 GB
      Boot ROM Version: MBP143.0175.B00
      SMC Version (system): 2.45f0
      Serial Number (system): C02VH0QYHTDG
      Hardware UUID: CE3BD703-13DB-5D1D-8413-B9E7A0FF2B5A

Thunderbolt:

    Thunderbolt Bus 1:

      Vendor Name: Apple Inc.
      Device Name: MacBook Pro
      UID: 0x0001A0DC3C124701
      Route String: 0
      Firmware Version: 33.1
      Domain UUID: 3440CB97-0C49-F651-9406-FEF1C3F18EBB
      Port:
          Status: No device connected
          Link Status: 0x101
          Speed: Up to 40 Gb/s x1
          Current Link Width: 0x1
          Receptacle: 4
          Link Controller Firmware Version: 0.35.0
      Port:
          Status: No device connected
          Link Status: 0x101
          Speed: Up to 40 Gb/s x1
          Current Link Width: 0x1
          Receptacle: 3
          Link Controller Firmware Version: 0.35.0

    Thunderbolt Bus 0:

      Vendor Name: Apple Inc.
      Device Name: MacBook Pro
      UID: 0x0001A0DC3C124700
      Route String: 0
      Firmware Version: 33.1
      Domain UUID: 685364AE-D0A4-2752-AC7F-1B11107808FA
      Port:
          Status: No device connected
          Link Status: 0x7
          Speed: Up to 40 Gb/s x1
          Current Link Width: 0x1
          Receptacle: 2
          Link Controller Firmware Version: 0.35.0
      Port:
          Status: Device connected
          Link Status: 0x2
          Speed: Up to 20 Gb/s x1
          Current Link Width: 0x1
          Receptacle: 1
          Link Controller Firmware Version: 0.35.0

        HP Thunderbolt 3 Dock - Unsupported:

          Vendor Name: HP Inc.
          Device Name: HP Thunderbolt 3 Dock - Unsupported
          Vendor ID: 0xF0
          Device ID: 0x8190
          Device Revision: 0x1
          UID: 0x00F04F4185121200
          Route String: 3
          Firmware Version: 16.1

UserClients() - 0
+ IOAudioEngine[<ptr>]::startAudioEngine(state = 0)
+ IOAudioDevice[<ptr>]::protectedCompletePowerStateChange() - current = 2 - pending = 2
- IOAudioDevice[<ptr>]::protectedCompletePowerStateChange() - current = 2 - pending = 2 returns 0x0
+ IOAudioDevice[<ptr>]::protectedCompletePowerStateChange() - current = 2 - pending = 2
- IOAudioDevice[<ptr>]::protectedCompletePowerStateChange() - current = 2 - pending = 2 returns 0x0
+ IOAudioDevice[<ptr>]::audioEngineStarting() - numRunningAudioEngines = 0
- IOAudioDevice[<ptr>]::audioEngineStarting() - numRunningAudioEngines = 1
+- IOAudioEngine[<ptr>]::resetStatusBuffer()
+-IOAudioEngine[<ptr>]::setState(0x1. oldState=0)
- IOAudioEngine[<ptr>]::getTimerInterval()
- IOAudioEngine[<ptr>]::startAudioEngine() returns 0x0
- IOAudioEngine[<ptr>]::incrementActiveUserClients() - 1 returns 0
- IOAudioEngine[<ptr>]::startClient(<ptr>) returns 0x0
  engine started 
  bufferSet <ptr> 
  output clientBuffer <ptr> 
+ IOAudioStream[<ptr>]::addClient(<ptr>)
- IOAudioStream[<ptr>]::addClient(<ptr>) returns 0x0
- IOAudioEngineUserClient[<ptr>]::startClient() - 1 returns 0x0
- IOAudioEngineUserClient::externalMethod returns 0x0
+ IOAudioEngineUserClient::externalMethod, selector=0x4,   arg0 0x0, arg1 0x0, arg2 0x0 arg3 0x0 
  scalarInputCount=0x0  structureInputSize 0x0, scalarOutputCount 0x0, structureOutputSize 0x0 
+ IOAudioStream[<ptr>]::removeClient(<ptr>)
+-IOAudioStream[<ptr>]::safeLogError kErrorLogDumpCounters mStreamErrorCountsUpdated=0
- IOAudioStream[<ptr>]::removeClient(<ptr>)
+- IOAudioEngine[<ptr>]::decrementActiveUserClients() - 0 returns 0x0
+- IOAudioEngine[<ptr>]::stopClient(<ptr>) returns 0x0
+- IOAudioEngineUserClient[<ptr>]::setOnline(0)
- IOAudioEngineUserClient::externalMethod returns 0x0
+ IOAudioEngineUserClient::externalMethod, selector=0x1,   arg0 0x10C25E000, arg1 0x124, arg2 0x0 arg3 0x0 
  scalarInputCount=0x2  structureInputSize 0x0, scalarOutputCount 0x0, structureOutputSize 0x0 
+ IOAudioEngineUserClient[<ptr>]::unregisterClientBuffer64(0x<ptr>, 0x124)
  searching for sourceBuffer 0x10c25e000 
+- IOAudioEngineUserClient[<ptr>]::removeBufferSet(<ptr>)
+ IOAudioStream[<ptr>]::removeClient(<ptr>)
+-IOAudioStream[<ptr>]::safeLogError kErrorLogDumpCounters mStreamErrorCountsUpdated=0
- IOAudioStream[<ptr>]::removeClient(<ptr>)
- IOAudioEngineUserClient::unregisterClientBuffer64 no sourcebuffer returns 0x0
- IOAudioEngineUserClient::externalMethod returns 0x0
+ IOAudioEngine[<ptr>]::stopAudioEngine()
+-IOAudioEngine[<ptr>]::setState(0x0. oldState=0x1)
+ IOAudioDevice[<ptr>]::audioEngineStopped() - numRunningAudioEngines = 1
+ IOAudioDevice[<ptr>]::scheduleIdleAudioSleep: idleSleepDelayTime = ffffffffffffffffffffffff
- IOAudioDevice[<ptr>]::scheduleIdleAudioSleep: idleSleepDelayTime = ffffffffffffffffffffffff
- IOAudioDevice[<ptr>]::audioEngineStopped() - numRunningAudioEngines = 0
- IOAudioEngine[<ptr>]::stopAudioEngine() returns 0x0
+-IOAudioEngine[<ptr>]::setState(0x0. oldState=0)
_sendCommandGated (ep: 3): Sending USB buffer size: 17408 command: <ptr> [Repeated 3 times]_dataReceiveCompletion: (epIndex: 3, _state: 1) message received: hasBuffer: 1 messageLength: 8 dataLength: 92 waitForAck: 0 [Repeated 3 times]Sandbox: 3 duplicate reports for fseventsd allow file-read-metadata /private/var/folders/jm/ndh7fm955q5c2s1s_nhns03w0000gn/0/com.apple.nsurlsessiond/E8C9768780A371F36651AB699D884E881706B377/7FE0018496E8AE54A16695597D7D412340C54E52Sandbox: 1 duplicate report for fseventsd allow file-read-metadata /private/var/folders/jm/ndh7fm955q5c2s1s_nhns03w0000gn/0/com.apple.nsurlsessiond/E8C9768780A371F36651AB699D884E881706B377/7FE0018496E8AE54A16695597D7D412340C54E52/tasks.plistSandbox: 5 duplicate reports for fseventsd allow file-read-metadata /private/var/folders/jm/ndh7fm955q5c2s1s_nhns03w0000gn/0/com.apple.nsurlsessiond/E8C9768780A371F36651AB699D884E881706B377/7FE0018496E8AE54A16695597D7D412340C54E52Thunderbolt3Unblocker: Refusing to load on OS version 17.6.0
Kext es.govost.ryan.Thunderbolt3Unblocker start failed (result 0x5).
Kext es.govost.ryan.Thunderbolt3Unblocker failed to load (0xdc008017).
Failed to load kext es.govost.ryan.Thunderbolt3Unblocker (error 0xdc008017).
+ IOAudioEngine[<ptr>]::newUserClient(0x<ptr>, <ptr>, 0x0, 0, <ptr>)
+ IOAudioEngineUserClient[<ptr>]::initWithAudioEngine(<ptr>, 0x<ptr>, <ptr>, 0x0, 0)
+- IOAudioEngineUserClient[<ptr>]::setOnline(0)
  ConnectionID:0xd89d85ca
- IOAudioEngineUserClient[<ptr>]::initWithAudioEngine(<ptr>, 0x<ptr>, <ptr>, 0x0, 0) returns 1
+- IOAudioEngineUserClient::withAudioEngine(<ptr>, 0x<ptr>, <ptr>, 0x0, 0) returns <ptr>
+ IOAudioEngine::addUserClientAction(<ptr>, <ptr>)
+- IOAudioEngine[<ptr>]::addUserClient(<ptr>) returns 0x0
- IOAudioEngine::addUserClientAction(<ptr>, <ptr>) returns 0x0
- IOAudioEngine[<ptr>]::newUserClient(0x<ptr>, <ptr>, 0x0, 0, <ptr>)
- IOAudioEngineUserClient[<ptr>]::registerFormatNotification(0x<ptr>, 0x100) returns 0x0
- IOAudioEngineUserClient::registerNotificationAction(<ptr>, <ptr>) returns 0x0
- IOAudioEngineUserClient[<ptr>]::registerNotificationPort(0x<ptr>, 0x0, 0x100) returns 0x0
Starting poll type 4
Restarting poll type 4
Command 0x2 completed. inCount: 2 data:0x5Command 0x1 completed. inCount: 2 data:0x1001Command 0x16 completed. inCount: 2 data:0x40e0Command 0xa completed. inCount: 2 data:0x0Command 0xb completed. inCount: 2 data:0x0Command 0x12 completed. inCount: 2 data:0xffffCommand 0x13 completed. inCount: 2 data:0xffffCommand 0xf completed. inCount: 2 data:0x1867Command 0x10 completed. inCount: 2 data:0x1899SmartBattery: finished polling type 4
Thunderbolt3Unblocker: Refusing to load on OS version 17.6.0
Kext es.govost.ryan.Thunderbolt3Unblocker start failed (result 0x5).
Kext es.govost.ryan.Thunderbolt3Unblocker failed to load (0xdc008017).
Failed to load kext es.govost.ryan.Thunderbolt3Unblocker (error 0xdc008017).
find_next_non_dataless_snapshot:654: apfs: next = 7586393 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7655418 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7655796 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7656192 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7673941 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7675501 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7676073 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7676923 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7677225 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7678594 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7679229 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7679606 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 18446744073709551615 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7655418 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7655796 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7656192 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7673941 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7675501 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7676073 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7676923 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7677225 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7678594 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7679229 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 7679606 err = -1
find_next_non_dataless_snapshot:654: apfs: next = 18446744073709551615 err = -1
Sandbox: 1 duplicate report for fseventsd allow file-read-metadata /private/var/folders/jm/ndh7fm955q5c2s1s_nhns03w0000gn/0/com.apple.nsurlsessiond/E8C9768780A371F36651AB699D884E881706B377/7FE0018496E8AE54A16695597D7D412340C54E52/tasks.plistSandbox: 7 duplicate reports for fseventsd allow file-read-metadata /private/var/folders/jm/ndh7fm955q5c2s1s_nhns03w0000gn/0/com.apple.nsurlsessiond/E8C9768780A371F36651AB699D884E881706B377Starting poll type 4
Restarting poll type 4
Command 0x2 completed. inCount: 2 data:0x5Command 0x1 completed. inCount: 2 data:0x1001Command 0x16 completed. inCount: 2 data:0x40e0Command 0xa completed. inCount: 2 data:0x0Command 0xb completed. inCount: 2 data:0x0Command 0x12 completed. inCount: 2 data:0xffffCommand 0x13 completed. inCount: 2 data:0xffffCommand 0xf completed. inCount: 2 data:0x1867Command 0x10 completed. inCount: 2 data:0x1899SmartBattery: finished polling type 4
+ IOAudioEngine[<ptr>]::newUserClient(0x<ptr>, <ptr>, 0x0, 0, <ptr>)
+ IOAudioEngineUserClient[<ptr>]::initWithAudioEngine(<ptr>, 0x<ptr>, <ptr>, 0x0, 0)
+- IOAudioEngineUserClient[<ptr>]::setOnline(0)
  ConnectionID:0x6eadc529
- IOAudioEngineUserClient[<ptr>]::initWithAudioEngine(<ptr>, 0x<ptr>, <ptr>, 0x0, 0) returns 1
+- IOAudioEngineUserClient::withAudioEngine(<ptr>, 0x<ptr>, <ptr>, 0x0, 0) returns <ptr>
+ IOAudioEngine::addUserClientAction(<ptr>, <ptr>)
+- IOAudioEngine[<ptr>]::addUserClient(<ptr>) returns 0x0
- IOAudioEngine::addUserClientAction(<ptr>, <ptr>) returns 0x0
- IOAudioEngine[<ptr>]::newUserClient(0x<ptr>, <ptr>, 0x0, 0, <ptr>)
- IOAudioEngineUserClient[<ptr>]::registerFormatNotification(0x<ptr>, 0x100) returns 0x0
- IOAudioEngineUserClient::registerNotificationAction(<ptr>, <ptr>) returns 0x0
- IOAudioEngineUserClient[<ptr>]::registerNotificationPort(0x<ptr>, 0x0, 0x100) returns 0x0
AGC:: [com.apple.WebKit pid:1413 mux-aware] starting, non-mux-aware app count 0 WS-ready 1 switch-state 0 IG FBs 1 EG FBs 0:0 power-state 6 3D idle HDA idle
AGC:: [com.apple.WebKit pid 1413 mux-aware] exiting, non-mux-aware app count 0, runtime: 0:00:00.000
AGC:: [com.apple.WebKit pid:1413 mux-aware] starting, non-mux-aware app count 0 WS-ready 1 switch-state 0 IG FBs 1 EG FBs 0:0 power-state 6 3D idle HDA idle
AGC:: :::::::> PEG start powerup [3m 11.331s downtime]
[IGFB][INFO   ] [key:0x420/on:0] fPSREnablekeys: 0x00001fff -> 0x00001bdf (fullset:0x00001fff) : Will disable FIFO PSR feature in 2sec
AGC:: *******> PEG powerup took: 0.405s
AGC:: [com.apple.WebKit pid 1413 mux-aware] exiting, non-mux-aware app count 0, runtime: 0:00:01.315
+- IOAudioEngine[<ptr>]::removeUserClient(<ptr>) returns 0x0
+- IOAudioEngine::removeUserClientAction(<ptr>, <ptr>) returns 0x0
+- IOAudioEngine[<ptr>]::clientClosed(<ptr>)
+- IOAudioEngineUserClient[<ptr>]::clientDied() returns 0x0
+- IOAudioEngineUserClient[<ptr>]::stop(<ptr>)
+ IOAudioEngine[<ptr>]::newUserClient(0x<ptr>, <ptr>, 0x0, 0, <ptr>)
+ IOAudioEngineUserClient[<ptr>]::initWithAudioEngine(<ptr>, 0x<ptr>, <ptr>, 0x0, 0)
+- IOAudioEngineUserClient[<ptr>]::setOnline(0)
  ConnectionID:0x67d086cd
- IOAudioEngineUserClient[<ptr>]::initWithAudioEngine(<ptr>, 0x<ptr>, <ptr>, 0x0, 0) returns 1
+- IOAudioEngineUserClient::withAudioEngine(<ptr>, 0x<ptr>, <ptr>, 0x0, 0) returns <ptr>
+ IOAudioEngine::addUserClientAction(<ptr>, <ptr>)
+- IOAudioEngine[<ptr>]::addUserClient(<ptr>) returns 0x0
- IOAudioEngine::addUserClientAction(<ptr>, <ptr>) returns 0x0
- IOAudioEngine[<ptr>]::newUserClient(0x<ptr>, <ptr>, 0x0, 0, <ptr>)
- IOAudioEngineUserClient[<ptr>]::registerFormatNotification(0x<ptr>, 0x100) returns 0x0
- IOAudioEngineUserClient::registerNotificationAction(<ptr>, <ptr>) returns 0x0
- IOAudioEngineUserClient[<ptr>]::registerNotificationPort(0x<ptr>, 0x0, 0x100) returns 0x0
AGC:: [com.apple.WebKit pid:1414 mux-aware] starting, non-mux-aware app count 0 WS-ready 1 switch-state 0 IG FBs 1 EG FBs 0:1f power-state 0 3D idle HDA idle
AGC:: [com.apple.WebKit pid 1414 mux-aware] exiting, non-mux-aware app count 0, runtime: 0:00:00.000
AGC:: [com.apple.WebKit pid:1414 mux-aware] starting, non-mux-aware app count 0 WS-ready 1 switch-state 0 IG FBs 1 EG FBs 0:1f power-state 0 3D idle HDA idle
AGC:: [com.apple.WebKit pid:1414] force EG up last PID 1414 WS-ready 1 switch-state 0 IG FBs 1 EG FBs 0:1f power-state 0 3D busy HDA idle
AGC:: mux-regs 4 3 5f 1f 0 8 severity 0 WS-ready 1 switch-state 0 IG FBs 1 EG FBs 0:1f power-state 0 3D idle HDA idle : AGC Dump State Timer
Sound assertion in AppleGFXHDAController at line 9150
Sound assertion in AppleGFXHDAController at line 9151
AGC:: :::::::> PEG start powerdown [0m 7.959s uptime]
[IGFB][INFO   ] [key:0x020/on:1] fPSREnablekeys: 0x00001bdf -> 0x00001bff (fullset:0x00001fff)
[IGFB][INFO   ] [key:0x400/on:1] fPSREnablekeys: 0x00001bff -> 0x00001fff (fullset:0x00001fff) : Enable FIFO PSR feature
AGC:: *******> PEG powerdown took: 0.452s
AGC:: mux-regs 4 0 20 0 0 8 severity 0 WS-ready 1 switch-state 0 IG FBs 1 EG FBs 0:0 power-state 6 3D idle HDA idle : AGC Dump State Timer
Starting poll type 4
Restarting poll type 4
Command 0x2 completed. inCount: 2 data:0x5Command 0x1 completed. inCount: 2 data:0x1001Command 0x16 completed. inCount: 2 data:0x40e0Command 0xa completed. inCount: 2 data:0x0Command 0xb completed. inCount: 2 data:0x0Command 0x12 completed. inCount: 2 data:0xffffCommand 0x13 completed. inCount: 2 data:0xffffCommand 0xf completed. inCount: 2 data:0x1867Command 0x10 completed. inCount: 2 data:0x1899SmartBattery: finished polling type 4
+ IOAudioEngine[<ptr>]::newUserClient(0x<ptr>, <ptr>, 0x0, 0, <ptr>)
+ IOAudioEngineUserClient[<ptr>]::initWithAudioEngine(<ptr>, 0x<ptr>, <ptr>, 0x0, 0)
+- IOAudioEngineUserClient[<ptr>]::setOnline(0)
  ConnectionID:0x7c85149a
- IOAudioEngineUserClient[<ptr>]::initWithAudioEngine(<ptr>, 0x<ptr>, <ptr>, 0x0, 0) returns 1
+- IOAudioEngineUserClient::withAudioEngine(<ptr>, 0x<ptr>, <ptr>, 0x0, 0) returns <ptr>
+ IOAudioEngine::addUserClientAction(<ptr>, <ptr>)
+- IOAudioEngine[<ptr>]::addUserClient(<ptr>) returns 0x0
- IOAudioEngine::addUserClientAction(<ptr>, <ptr>) returns 0x0
- IOAudioEngine[<ptr>]::newUserClient(0x<ptr>, <ptr>, 0x0, 0, <ptr>)
- IOAudioEngineUserClient[<ptr>]::registerFormatNotification(0x<ptr>, 0x100) returns 0x0
- IOAudioEngineUserClient::registerNotificationAction(<ptr>, <ptr>) returns 0x0
- IOAudioEngineUserClient[<ptr>]::registerNotificationPort(0x<ptr>, 0x0, 0x100) returns 0x0
Starting poll type 4
Restarting poll type 4
Command 0x2 completed. inCount: 2 data:0x5Command 0x1 completed. inCount: 2 data:0x1001Command 0x16 completed. inCount: 2 data:0x40e0Command 0xa completed. inCount: 2 data:0x0Command 0xb completed. inCount: 2 data:0x0Command 0x12 completed. inCount: 2 data:0xffffCommand 0x13 completed. inCount: 2 data:0xffffCommand 0xf completed. inCount: 2 data:0x1867Command 0x10 completed. inCount: 2 data:0x1899SmartBattery: finished polling type 4
+- IOAudioEngine[<ptr>]::removeUserClient(<ptr>) returns 0x0
+- IOAudioEngine::removeUserClientAction(<ptr>, <ptr>) returns 0x0
+- IOAudioEngine[<ptr>]::clientClosed(<ptr>)
+- IOAudioEngineUserClient[<ptr>]::clientDied() returns 0x0
+- IOAudioEngineUserClient[<ptr>]::stop(<ptr>)
Starting poll type 4
Restarting poll type 4
Command 0x2 completed. inCount: 2 data:0x5Command 0x1 completed. inCount: 2 data:0x1001Command 0x16 completed. inCount: 2 data:0x40e0Command 0xa completed. inCount: 2 data:0x0Command 0xb completed. inCount: 2 data:0x0Command 0x12 completed. inCount: 2 data:0xffffCommand 0x13 completed. inCount: 2 data:0xffffCommand 0xf completed. inCount: 2 data:0x1867Command 0x10 completed. inCount: 2 data:0x1899SmartBattery: finished polling type 4
Sandbox: 1 duplicate report for fseventsd allow file-read-metadata /private/var/folders/jm/ndh7fm955q5c2s1s_nhns03w0000gn/0/com.apple.nsurlsessiond/E8C9768780A371F36651AB699D884E881706B377/sessions.plistSandbox: 3 duplicate reports for fseventsd allow file-read-metadata /private/var/folders/jm/ndh7fm955q5c2s1s_nhns03w0000gn/0/com.apple.nsurlsessiondSandbox: 3 duplicate reports for fseventsd allow file-read-metadata /private/var/folders/zz/zyxvpxvq6csfxvn_n00000y800007k/0/com.apple.nsurlsessiondKext es.govost.ryan.Thunderbolt3Unblocker not found for unload request.
Thunderbolt3Unblocker: Refusing to load on OS version 17.6.0
Kext es.govost.ryan.Thunderbolt3Unblocker start failed (result 0x5).
Kext es.govost.ryan.Thunderbolt3Unblocker failed to load (0xdc008017).
Failed to load kext es.govost.ryan.Thunderbolt3Unblocker (error 0xdc008017).
Thunderbolt3Unblocker: Refusing to load on OS version 17.6.0
Kext es.govost.ryan.Thunderbolt3Unblocker start failed (result 0x5).
Kext es.govost.ryan.Thunderbolt3Unblocker failed to load (0xdc008017).
Failed to load kext es.govost.ryan.Thunderbolt3Unblocker (error 0xdc008017).

**Comment by rgov** [comment]
Thunderbolt 3 Unblocker contains a protection so that if the system crashes while it loads, it will not load again on the same version of macOS. You can reset this with `nvram -d t3u-incompatible`. However, I would like to see a kernel panic report from when it was loaded, to understand why it failed on your system, and there is not one attached.

**Comment by langxiaopiao030** [comment]
I ran the command "nvram -d t3u-incompatible" but it was still no go

**Comment by langxiaopiao030** [comment]
I ran the command "nvram -d t3u-incompatible" but it was still no go
Are these log files？
[mbbservice_2019-12-04-142057_godmbp.crash.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/3920362/mbbservice_2019-12-04-142057_godmbp.crash.txt)
[mbbservice_2019-12-04-142047_godmbp.crash.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/3920363/mbbservice_2019-12-04-142047_godmbp.crash.txt)

**Comment by rgov** [comment]
No the filenames would start with “Kernel”. 

Can you run the diagnostic script again and drag t3u-diagnose.txt to the comment box to attach it?

**Comment by langxiaopiao030** [comment]
I ran it again, and it was a success, amuuuu. Thank you very much for the Unlocker.
<img width="302" alt="屏幕快照 2019-12-05 下午8 21 38" src="https://user-images.githubusercontent.com/37826868/70235228-7cd72400-179d-11ea-9818-c7644abe6cbc.png">
