### ISSUE TITLE
A Error may be 

### ISSUE THREAD

**Issue by dale19900108** [rgov/Thunderbolt3Unblocker#52]
MacBook Pro (15-inch, 2018)   
OSVersion 10.15.3  
the computer automatically into the screen saver after a day work in  office . When get to work in the morning, have a 90% chance of crashing.
here is the crash log ，may help you  
[error.log](https://github.com/rgov/Thunderbolt3Unblocker/files/4357789/error.log)

**Comment by rgov** [comment]
I don't think this is related. The issue is that the WindowServer is not responding for 2 minutes so the system panics. If there were an issue with Thunderbolt 3 Unblocker, it would most likely panic immediately when it is loaded, not later on.
