### ISSUE TITLE
Maybe can‘t work on 10.15.4

### ISSUE THREAD

**Issue by feiyunroc** [rgov/Thunderbolt3Unblocker#53]
Last week update to 10.15.4，my tb3 dock show unsupport on ioreg tree，can you fix it？

**Comment by grradams** [comment]
Same here. No go on 10.15.4

**Comment by rgov** [comment]
Please file this issue again following the instructions in the issue template, which is also on the wiki, which is also on the main page of this project. I cannot diagnose without any details. https://github.com/rgov/Thunderbolt3Unblocker/wiki/Troubleshooting
