### ISSUE TITLE
Kext with invalid signature (-67050) denied: macOS Catalina 10.15.4

### ISSUE THREAD

**Issue by Sam01101101** [rgov/Thunderbolt3Unblocker#55]
Hi There, 

I'm getting the following error: Kext with invalid signature (-67050) denied: /Library/StagedExtensions/Library/Extensions/CA9F0B92-19E6-4794-898E-11FD69AB76F3.kext
 
Error Message from Terminal Below: 
[terminallog.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/4613322/terminallog.txt)

Full Diagnostic Log below:
[t3u-diagnose.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/4613310/t3u-diagnose.txt)

Your help would be much appreciated

**Comment by rgov** [comment]
System Integrity Protection: Enabled

Please follow instructions to disable System Integrity Protection for kernel extensions.

**Comment by Sam01101101** [comment]
Thanks rgov, I didn't realise i had to disable system integrity prot before installing the extension. 

confirming its working well with 10.15.4
