### ISSUE TITLE
mac catalina 10.15.5 not work

### ISSUE THREAD

**Issue by Elson8080** [rgov/Thunderbolt3Unblocker#57]
Do everything from guides in the latest release.
Still has the result: HP Thunderbolt 3 Dock - Unsupported

HP Thunderbolt 3 Dock - Unsupported:
  Vendor Name:	HP Inc.
  Device Name:	HP Thunderbolt 3 Dock - Unsupported
  Vendor ID:	0xF0
  Device ID:	0x8190
  Device Revision:	0x1
  UID:	---
  Route String:	3
  Firmware Version:	16.1

Is the guides not fit for mac 10.15.5?
if yes, how could I do, thx

**Comment by rgov** [comment]
You didn't follow the instructions on [the Troubleshooting page](https://github.com/rgov/Thunderbolt3Unblocker/wiki/Troubleshooting) which was requested when you filed the issue.

**Comment by Elson8080** [comment]
It's work, thx
the system report shows thunder unsupported
However, just use it, it works, thx
