### ISSUE TITLE
mac os Catalina 10.15.6 seems not work

### ISSUE THREAD

**Issue by Elson8080** [rgov/Thunderbolt3Unblocker#58]
[t3u-diagnose.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/5153877/t3u-diagnose.txt)

However，yesterday my mac is still Catalina 10.15.5 and I do every right thing by following the guide. The power is okay. The display show the second table.

But the display screen shows black in every 10 seconds. Maybe my os version is not supported，so I upgrade to 10.15.6 and it still don't work

**Comment by rgov** [comment]
Can you reboot and try again?

**Comment by Elson8080** [comment]
Okay，I tried，here is the code response
![image](https://user-images.githubusercontent.com/16133652/92233998-d95da000-eee3-11ea-9b4b-6be4d69bbfd3.png)

bug report
[t3u-diagnose.txt](https://github.com/rgov/Thunderbolt3Unblocker/files/5174480/t3u-diagnose.txt)

the system info
![image](https://user-images.githubusercontent.com/16133652/92234133-145fd380-eee4-11ea-9ed8-ff9a16fb5bcb.png)

and the power is okay，mac is recharged
But the display is black forever

However my partner's mac is working well which is Mac OS Catalina 10.15.2

**Comment by rgov** [comment]
Your diagnostics file says that there is no device plugged in on Thunderbolt. Ordinarily it would tell us what device is plugged in, even if the system is blocking this device. So this issue does not seem to be related to Thunderbolt 3 Unblocker, just your device.

**Comment by rgov** [comment]
Perhaps you are not using a proper Thunderbolt 3 cable, and it's just a USB-C cable?
