### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by 240281488** [rgov/Thunderbolt3Unblocker#59]
Hi, rgov . Thank you for writing this code. I have some problems and need your help.
My MacBook Pro 2019. OS 10.15.6 。 The expansion is  HP elite thunderbolt 3 dock / HP zbook thunderbolt 3 dock, hq-tre, 71025 Boeblingen, Germany
. I'm downloading https://github.com/rgov/Thunderbolt3Unblocker/releases/tag/v0.0.4   In this version, my power adapter makes a sound and can be charged. The mouse can follow my hand, but the left button will be abnormal (for example, when I move my mouse to finder, the mouse will be on its own)

**Comment by 240281488** [comment]
@rgov

**Comment by rgov** [comment]
First, please follow all of the instructions on the [Troubleshooting](https://github.com/rgov/Thunderbolt3Unblocker/wiki/Troubleshooting) page.

Thunderbolt 3 Unblocker *unblocks* macOS from trying to load drivers for the dock. However, it does not *provide* drivers for your devices. So any problem with misbehaving devices is not caused (or solved) with this software.

I suggest trying a different mouse.
