### ISSUE TITLE
Catalina 10.15.6

### ISSUE THREAD

**Issue by snowspirit** [rgov/Thunderbolt3Unblocker#60]
This was noted in the other issues thread about the Dell TB16 by @micahqcade - I couldn't get this to work on MacOS Catalina 10.15.6 however the following got it to work (using with an HP Elite Thunderbolt 3 dock - with supplied T3/power adapter):

If/when you update to macOS Catalina 10.15.6 you have disable SIP again, rerun the command

"
sudo sh -c 'chown -R root:wheel /Library/Extensions/Thunderbolt3Unblocker.kext &&
chmod -R g-w,o-w /Library/Extensions/Thunderbolt3Unblocker.kext &&
kextcache -i / &&
nvram -d t3u-incompatible &&
kextload -b es.govost.ryan.Thunderbolt3Unblocker'
"
and reboot, then the dock should work. I just updated to 10.15.6 and the kext stopped working even though it was still in the
Library/extensions folder

**Comment by WibbleWorks** [comment]
I have had this on my company laptop every time there has been an update.
Today, after updating to 10.15.7 this week, I can not get the script to run for my HP Elite Thunderbolt 3

**Comment by rgov** [comment]
@snowspirit Thanks. This looks similar to what the instructions say now, let me know if I should update the instructions?

@WibbleWorks please file a new issue and follow the Troubleshooting steps (found under the Wiki tab). It is important to attach the requested diagnostic.

Just so you know, the writing is on the wall for this. Apple is trying to shut down the manner by which the tool operates.
