### ISSUE TITLE
It doesn't seem to work in macOS big sur

### ISSUE THREAD

**Issue by raychou1994** [rgov/Thunderbolt3Unblocker#61]
today i update my mbp 2016 to 11.0.1 and my hp elite thunderbolt3 dock doesn't work.

**Comment by rgov** [comment]
Please follow the directions when submitting an issue so that it is possible to diagnose the problem.

**Comment by 251305060** [comment]
l try it on MacBook Air 2020 m1, but it says
Not rebuilding KC for arch: 'arm64e'
kmutil done
Executing: /usr/bin/kmutil load -b es.govost.ryan.Thunderbolt3Unblocker
Incompatible architecture: Binary is for x86_64, but needed arch arm64e
Seems that it does't work on arm Mac
