### ISSUE TITLE
Intel platform  macOS11.2 versions Unlock the failure Problem

### ISSUE THREAD

**Issue by RenLishisan** [rgov/Thunderbolt3Unblocker#66]
**I am in Intel platform  macOS11.2 Versions unlock Thunderbolt 3 Encountering a problem with an unlocking failure。**
Currently, the Mac recognizes the device, but it can only use the charging function, and no other extension functions are available.
I executed the document directive, and the following error occurred:
```
Executing: /usr/bin/kmutil load -b es.govost.ryan.Thunderbolt3Unblocker
Error Domain=KMErrorDomain Code=27 "Extension with identifiers es.govost.ryan.Thunderbolt3Unblocker not approved to load. Please approve using System Preferences." UserInfo={NSLocalizedDescription=Extension with identifiers es.govost.ryan.Thunderbolt3Unblocker not approved to load. Please approve using System Preferences.}
```

**Comment by rgov** [comment]
Please use the Security preference pane in System Preferences to approve the extension.

**Comment by RenLishisan** [comment]
Hello, thank you very much for replying to me. I have successfully executed the command according to your tips, but I am not sure whether it was successful or not.
<img width="570" alt="WeChat7c0628c98bd33ded17b73b060e040faa" src="https://user-images.githubusercontent.com/48661664/107184571-c82d3800-6a1b-11eb-982b-1e9a395c516e.png">
The computer can recognize the docking station properly before I unlock it, but I can only use the charging function, and other extension functions cannot be used, and this is still the case after I unlock it.

Ask the author, is this the reason for unlocking the file?

My extension device is: `HP Thunderbolt 3 dock`、`macOS Big Sur 11.2`、`Intel Core i5`、`2020edition`.

**Comment by RenLishisan** [comment]
I have solved this problem now, and I don't know how to solve it. I will close ISP and restart it, and then install the unlock file again.

Try several times, restart the machine, and then is ready to give up when the insertion of the DP + + interface video signal, suddenly found that has been successfully unlocked.
<img width="1302" alt="WechatIMG183" src="https://user-images.githubusercontent.com/48661664/107187778-7edfe700-6a21-11eb-8f5f-7add556ecf8a.png">

**Thank you very much for the unlock file！**
