### ISSUE TITLE
Monterey working

### ISSUE THREAD

**Issue by Azero-NG** [rgov/Thunderbolt3Unblocker#72]
![image](https://user-images.githubusercontent.com/21135073/140888906-14bfff2b-eb9d-448d-a118-3f028a37a540.png)
![image](https://user-images.githubusercontent.com/21135073/140889008-aa9d5d5a-0a23-4374-85ed-d172098cc570.png)

usb is ok

**Comment by wheelerlaw** [comment]
Ethernet works too?

**Comment by Azero-NG** [comment]
yes

**Comment by rgov** [comment]
Glad it works.
