### ISSUE TITLE
HP thunderbolt 3 Dock Working well (macOS Monterey)

### ISSUE THREAD

**Issue by ARKepl** [rgov/Thunderbolt3Unblocker#73]
![截屏2021-12-04 下午2 37 02](https://user-images.githubusercontent.com/95535670/144713440-84480156-b514-4bd3-87c8-db699ecde857.png
![截屏2021-12-04 下午2 38 15](https://user-images.githubusercontent.com/95535670/144713471-780a876d-c004-449b-99e2-44f3715fb9db.png)
)

**Comment by ARKepl** [comment]
Ethernet works well
Audio works well
Video output support 4K@60
USB works well

**Comment by ARKepl** [comment]
![截屏2021-12-04 下午2 37 02](https://user-images.githubusercontent.com/95535670/144713698-e95c9bd0-565d-48c6-81f2-fee2460c194e.png)

**Comment by rgov** [comment]
Thanks for the report.
