### ISSUE TITLE
OSX Monterey - BridgeOS Crashes 

### ISSUE THREAD

**Issue by xpwn3rx** [rgov/Thunderbolt3Unblocker#74]
I'm getting crashes (kernel panics) on OSX Monterey that are tagged as bug_type 210. Apple support pointed the finger at this kext and told me to remove it to stop the crashes. The 210 code seems to indicate a memory issue.

Removing the kext is not possible as I'm using this kext with a Dell Tunderbolt TB16 dock and need the kext to make the dock work. I would prefer not to upload the IPS dump files here because I see a lot of information that should not be made public in there. If that is of value to you for investigation, I can probably redact some sensitive details from it and upload to you.

**Comment by rgov** [comment]
I cannot diagnose anything without looking at logs. There is a script to collect logs in the Wiki tab. If you would like you can email logs to rgovostes+git@gmail.com.
