### ISSUE TITLE
Extension is not automatically loaded after reboot

### ISSUE THREAD

**Issue by Dime2015** [rgov/Thunderbolt3Unblocker#9]
Kernel extension have to be reloaded every time after reboot, have tried move it into systems/library/extensions, doesn't work.
I am not very familiar with this technique, any chance to make this kernel extension load automatically after reboot?
Many thanks!

**Comment by rgov** [comment]
I'll need some more information. What "doesn't work" about moving it into /System/Library/Extensions?

**Comment by Dime2015** [comment]
My machine is macbook pro 2016 with 2tbt
OS version is 10.13.4
Every time I reboot my Mac, my thunderbolt3 dock will be unable to be recognized, I have to use Terminal to "sudo kextload" this .kext file in order to make my mac recognized my unsupported dock.

**Comment by rgov** [comment]
Right, macOS doesn't load kernel extensions automatically except for the ones in /System/Library/Extensions. But I'm not sure why you are unable to move the file there.

```
sudo mv Thunderbolt3Unblocker.kext /System/Library/Extensions
```

If it fails, then maybe you need to disable System Integrity Protection?

**Comment by Dime2015** [comment]
I have moved this .kext to /System/Library/Extensions, but i still have to retype "sudo kextload" to get it into work after rebooting.

**Comment by rgov** [comment]
Perhaps this article is relevant? [User-Approved Kernel Extension Loading](https://developer.apple.com/library/content/technotes/tn2459/_index.html)

Is there anything in the system log after rebooting that gives a reason for why the kext has not loaded?

**Comment by rgov** [comment]
[This answer](https://stackoverflow.com/a/36478163/145504) on StackOverflow says that generic kernel extensions are "only loaded either because another kext depends on them, or because they are explicitly loaded via kextutil/kextload or the KextManager API." So it seems that it would not be automatically loaded on boot.

I can make a change for this.

**Comment by Dime2015** [comment]
This seems to be the very reason.
Thank you so much!

**Comment by rgov** [comment]
Fixed in 3014f7a05717ad2972c19bf894484fb27e250400.

**Comment by Dime2015** [comment]
Build .kext with the new resources, not working.
Maybe out of this reason? [https://derflounder.wordpress.com/2017/08/24/kernel-extensions-and-macos-high-sierra/](url)

> macOS High Sierra

Kernel extensions must be digitally signed using an Apple Developer ID for Signing Kexts certificate and installed into /Library/Extensions. System Integrity Protection remains the enforcement mechanism. Kernel extensions will not load unless authorized to do so by a logged-in user.

Note: This authorized user does not need to have admin rights, so any logged-in user can authorize the loading of a kernel extension.

**Comment by rgov** [comment]
Please give more information beyond "not working." I have no possible way to diagnose the problem for you without more details.  Do you mean that you downloaded the new source, re-compiled the kext, placed it in /System/Library/Extensions (or /Library/Extensions), and then rebooted, and it did not load?

Can you run `sudo kextutil -nt Thunderbolt3Unblocker.kext` and paste its output, and the output of `sudo kextstat` on gist.github.com and link the result here?

**Comment by Dime2015** [comment]
Yes, as you said, that's what I mean.

All these information are generated after I manually kextload the .text after reboot.

Kext with invalid signatured (-67050) allowed: <OSKext 0x7f86f453f660 [0x7fff8d477af0]> { URL = "file:///System/Library/Extensions/Thunderbolt3Unblocker.kext/", ID = "es.govost.ryan.Thunderbolt3Unblocker" }
Kext with invalid signatured (-67054) allowed: <OSKext 0x7f86f4532120 [0x7fff8d477af0]> { URL = "file:///System/Library/Extensions/IOThunderboltFamily.kext/", ID = "com.apple.iokit.IOThunderboltFamily" }
Code Signing Failure: code signature is invalid
/System/Library/Extensions/Thunderbolt3Unblocker.kext appears to be loadable (including linkage for on-disk libraries).

https://gist.github.com/Dime2015/ebfa67e8854f10dd5bcd406128638f65

**Comment by rgov** [comment]
156    0 0xffffff7f838c7000 0x4f000    0x4f000    es.govost.ryan.Thunderbolt3Unblocker (1) EA700925-2499-3733-B343-601AD8010A1A <63 7 5 4 1>

It looks like it loaded to me. What makes you think it didn't load?

**Comment by Dime2015** [comment]
I said, after reboot, it didn't loaded "automatically".
So, I loaded it manually, means typing "sudo kextload .kext" in terminal by myself.

If you want my kextstat after a reboot but before I load this .kext by myself manually, I can generate another result for you.
By the way, I have a outdated TI82 thunderbolt3 dock which need this thunderbolt3unblocker, so I can tell whether it is loaded or not from my external monitor which is plugged in my dock.

**Comment by rgov** [comment]
The code signing error should not be a problem if you have disabled SIP kext validation (`csrutil enable --without kext`).

Yes, I'd like to see `kextstat` after you reboot to confirm that it's not loaded (whether or not the external monitor comes up).

Please also `cat /System/Library/Extensions/Thunderbolt3Unblocker.kext/Contents/Info.plist` (or /Library if that's where you put it).

**Comment by Dime2015** [comment]
SIP has disabled
kextstat : https://gist.github.com/Dime2015/0cf6a7588e13a5fdaf665d3db03dbf02

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildMachineOSBuild</key>
	<string>17E199</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>Thunderbolt3Unblocker</string>
	<key>CFBundleIdentifier</key>
	<string>es.govost.ryan.Thunderbolt3Unblocker</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Thunderbolt3Unblocker</string>
	<key>CFBundlePackageType</key>
	<string>KEXT</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>DTCompiler</key>
	<string>com.apple.compilers.llvm.clang.1_0</string>
	<key>DTPlatformBuild</key>
	<string>9E145</string>
	<key>DTPlatformVersion</key>
	<string>GM</string>
	<key>DTSDKBuild</key>
	<string>17E189</string>
	<key>DTSDKName</key>
	<string>macosx10.13</string>
	<key>DTXcode</key>
	<string>0930</string>
	<key>DTXcodeBuild</key>
	<string>9E145</string>
	<key>IOKitPersonalities</key>
	<dict>
		<key>Thunderbolt3Unblocker</key>
		<dict>
			<key>CFBundleIdentifier</key>
			<string>es.govost.ryan.Thunderbolt3Unblocker</string>
			<key>IOClass</key>
			<string>IOService</string>
			<key>IOProviderClass</key>
			<string>IOThunderboltController</string>
		</dict>
	</dict>
	<key>NSHumanReadableCopyright</key>
	<string>Copyright © 2018 Ryan Govostes. All rights reserved.</string>
	<key>OSBundleLibraries</key>
	<dict>
		<key>com.apple.iokit.IOThunderboltFamily</key>
		<string>1.0.0</string>
		<key>com.apple.kpi.bsd</key>
		<string>9.0</string>
		<key>com.apple.kpi.libkern</key>
		<string>9.0</string>
		<key>com.apple.kpi.mach</key>
		<string>9.0</string>
		<key>com.apple.kpi.unsupported</key>
		<string>9.0</string>
	</dict>
</dict>
</plist>

**Comment by rgov** [comment]
Please run `sudo kextcache -i /` after copying the kext into /System/Library/Extensions or /Library/Extensions and then run `strings /System/Library/PrelinkedKernels/prelinkedkernel  | grep Thunderbolt3Unblocker` to make sure the kext made it into the prelinked kernel.

**Comment by Dime2015** [comment]
After typing these commands in terminal, it will now be loaded automatically after rebooting. No need to sudo kextload .kext manually.
But I still have to unplug and plug the thunderbolt3 cable to make my mac recognize this dock every time after rebooting. Unsure it is because of my dock's deficiency or Thunderbolt3Unblocker itself.

**Comment by rgov** [comment]
Glad to hear. It's possible that the dock is being loaded before Thunderbolt3Unblocker is able to patch IOThunderboltFamily. I don't know how to make it patch any faster, but maybe there is a way to re-enumerate blocked devices? I'll try to find out.

**Comment by Dime2015** [comment]
Thank you for your patience and help in time! Learned a lot from your project.
